// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/homelab/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Homelab) MarshalJSON() ([]byte, error) {
	var concrete struct {
		DevenvSource *dagger.Directory
	}
	concrete.DevenvSource = r.DevenvSource
	return json.Marshal(&concrete)
}

func (r *Homelab) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		DevenvSource *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.DevenvSource = concrete.DevenvSource
	return nil
}

func (r DevenvProject) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Path   string
		Source *dagger.Directory
	}
	concrete.Path = r.Path
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *DevenvProject) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Path   string
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Path = concrete.Path
	r.Source = concrete.Source
	return nil
}

func (r GoModule) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Path   string
		Source *dagger.Directory
	}
	concrete.Path = r.Path
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *GoModule) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Path   string
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Path = concrete.Path
	r.Source = concrete.Source
	return nil
}

func (r HelmChart) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Path          string
		Source        *dagger.Directory
		ClusterValues *dagger.File
		SharedCharts  *dagger.Directory
	}
	concrete.Path = r.Path
	concrete.Source = r.Source
	concrete.ClusterValues = r.ClusterValues
	concrete.SharedCharts = r.SharedCharts
	return json.Marshal(&concrete)
}

func (r *HelmChart) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Path          string
		Source        *dagger.Directory
		ClusterValues *dagger.File
		SharedCharts  *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Path = concrete.Path
	r.Source = concrete.Source
	r.ClusterValues = concrete.ClusterValues
	r.SharedCharts = concrete.SharedCharts
	return nil
}

func (r PythonProject) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Path   string
		Source *dagger.Directory
	}
	concrete.Path = r.Path
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *PythonProject) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Path   string
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Path = concrete.Path
	r.Source = concrete.Source
	return nil
}

func (r TerraformModule) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Path   string
		Name   string
		Source *dagger.Directory
	}
	concrete.Path = r.Path
	concrete.Name = r.Name
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *TerraformModule) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Path   string
		Name   string
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Path = concrete.Path
	r.Name = concrete.Name
	r.Source = concrete.Source
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "DevenvProject":
		switch fnName {
		case "Update":
			var parent DevenvProject
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*DevenvProject).Update(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "GoModule":
		switch fnName {
		case "Lint":
			var parent GoModule
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var configFile *dagger.File
			if inputArgs["configFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["configFile"]), &configFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg configFile", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*GoModule).Lint(&parent, ctx, configFile, container)
		case "Test":
			var parent GoModule
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*GoModule).Test(&parent, ctx, container)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "HelmChart":
		switch fnName {
		case "Build":
			var parent HelmChart
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*HelmChart).Build(&parent, ctx, container)
		case "Kubeconform":
			var parent HelmChart
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*HelmChart).Kubeconform(&parent, ctx, container)
		case "Polaris":
			var parent HelmChart
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*HelmChart).Polaris(&parent, ctx, container)
		case "Validate":
			var parent HelmChart
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*HelmChart).Validate(&parent, ctx, container)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Homelab":
		switch fnName {
		case "BuildCli":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var paths []string
			if inputArgs["paths"] != nil {
				err = json.Unmarshal([]byte(inputArgs["paths"]), &paths)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg paths", err))
				}
			}
			return (*Homelab).BuildCli(&parent, ctx, source, paths)
		case "BuildCliGo":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Homelab).BuildCliGo(&parent, ctx, source)
		case "BuildHelm":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var paths []string
			if inputArgs["paths"] != nil {
				err = json.Unmarshal([]byte(inputArgs["paths"]), &paths)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg paths", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).BuildHelm(&parent, ctx, source, paths, container)
		case "Cli":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var platform dagger.Platform
			if inputArgs["platform"] != nil {
				err = json.Unmarshal([]byte(inputArgs["platform"]), &platform)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg platform", err))
				}
			}
			return (*Homelab).Cli(&parent, ctx, source, platform), nil
		case "CliNix":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Homelab).CliNix(&parent, ctx, source), nil
		case "DebugDir":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var dir *dagger.Directory
			if inputArgs["dir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dir"]), &dir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dir", err))
				}
			}
			return (*Homelab).DebugDir(&parent, ctx, dir), nil
		case "DevenvContainer":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var ws dagger.Workspace
			if inputArgs["ws"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ws"]), &ws)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ws", err))
				}
			}
			var nixDaemon *dagger.Socket
			if inputArgs["nixDaemon"] != nil {
				err = json.Unmarshal([]byte(inputArgs["nixDaemon"]), &nixDaemon)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg nixDaemon", err))
				}
			}
			var profiles []string
			if inputArgs["profiles"] != nil {
				err = json.Unmarshal([]byte(inputArgs["profiles"]), &profiles)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg profiles", err))
				}
			}
			return (*Homelab).DevenvContainer(&parent, ws, nixDaemon, profiles), nil
		case "DevenvProjects":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Homelab).DevenvProjects(&parent, ctx, source), nil
		case "ExportCue":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).ExportCue(&parent, ctx, source, container)
		case "FixCue":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).FixCue(&parent, source, container), nil
		case "FormatCue":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).FormatCue(&parent, source, container), nil
		case "FormatNix":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var paths []string
			if inputArgs["paths"] != nil {
				err = json.Unmarshal([]byte(inputArgs["paths"]), &paths)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg paths", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).FormatNix(&parent, source, paths, container), nil
		case "FormatPython":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var paths []string
			if inputArgs["paths"] != nil {
				err = json.Unmarshal([]byte(inputArgs["paths"]), &paths)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg paths", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).FormatPython(&parent, ctx, source, paths, container), nil
		case "FormatTerraform":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).FormatTerraform(&parent, source, container), nil
		case "GoModules":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Homelab).GoModules(&parent, ctx, source), nil
		case "HelmCharts":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Homelab).HelmCharts(&parent, ctx, source), nil
		case "LintGo":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).LintGo(&parent, ctx, source, container)
		case "LintPython":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var paths []string
			if inputArgs["paths"] != nil {
				err = json.Unmarshal([]byte(inputArgs["paths"]), &paths)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg paths", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).LintPython(&parent, ctx, source, paths, container)
		case "LintYaml":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var paths []string
			if inputArgs["paths"] != nil {
				err = json.Unmarshal([]byte(inputArgs["paths"]), &paths)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg paths", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).LintYaml(&parent, ctx, source, paths, container)
		case "PythonProjects":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Homelab).PythonProjects(&parent, ctx, source), nil
		case "TerraformModules":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Homelab).TerraformModules(&parent, ctx, source), nil
		case "TestBuildHelm":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Homelab).TestBuildHelm(&parent, ctx)
		case "TestBuildHelmWithDeps":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Homelab).TestBuildHelmWithDeps(&parent, ctx)
		case "TestGo":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).TestGo(&parent, ctx, source, container)
		case "TestHelmChartBuild":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Homelab).TestHelmChartBuild(&parent, ctx)
		case "TestHelmChartValidate":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Homelab).TestHelmChartValidate(&parent, ctx)
		case "TestPython":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var paths []string
			if inputArgs["paths"] != nil {
				err = json.Unmarshal([]byte(inputArgs["paths"]), &paths)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg paths", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).TestPython(&parent, ctx, source, paths, container)
		case "TestValidateHelm":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Homelab).TestValidateHelm(&parent, ctx)
		case "TrimCue":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).TrimCue(&parent, source, container), nil
		case "UpdateDevenv":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Homelab).UpdateDevenv(&parent, ctx, source)
		case "UpdateGoVendorHash":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Homelab).UpdateGoVendorHash(&parent, ctx, source)
		case "ValidateHelm":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var paths []string
			if inputArgs["paths"] != nil {
				err = json.Unmarshal([]byte(inputArgs["paths"]), &paths)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg paths", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).ValidateHelm(&parent, ctx, source, paths, container)
		case "ValidateKubeconform":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var paths []string
			if inputArgs["paths"] != nil {
				err = json.Unmarshal([]byte(inputArgs["paths"]), &paths)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg paths", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).ValidateKubeconform(&parent, ctx, source, paths, container)
		case "ValidateNix":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var paths []string
			if inputArgs["paths"] != nil {
				err = json.Unmarshal([]byte(inputArgs["paths"]), &paths)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg paths", err))
				}
			}
			return (*Homelab).ValidateNix(&parent, ctx, source, paths)
		case "ValidatePolaris":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var paths []string
			if inputArgs["paths"] != nil {
				err = json.Unmarshal([]byte(inputArgs["paths"]), &paths)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg paths", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).ValidatePolaris(&parent, ctx, source, paths, container)
		case "ValidateTerraform":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).ValidateTerraform(&parent, ctx, source, container)
		case "ValidateWoodpecker":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var paths []string
			if inputArgs["paths"] != nil {
				err = json.Unmarshal([]byte(inputArgs["paths"]), &paths)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg paths", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).ValidateWoodpecker(&parent, ctx, source, paths, container)
		case "VerifyCacheGranularity":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var run string
			if inputArgs["run"] != nil {
				err = json.Unmarshal([]byte(inputArgs["run"]), &run)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg run", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*Homelab).VerifyCacheGranularity(&parent, ctx, source, run, container)
		case "":
			var parent Homelab
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var devenvSource *dagger.Directory
			if inputArgs["devenvSource"] != nil {
				err = json.Unmarshal([]byte(inputArgs["devenvSource"]), &devenvSource)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg devenvSource", err))
				}
			}
			return New(devenvSource), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "PythonProject":
		switch fnName {
		case "Format":
			var parent PythonProject
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*PythonProject).Format(&parent, container), nil
		case "Lint":
			var parent PythonProject
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*PythonProject).Lint(&parent, ctx, container)
		case "Test":
			var parent PythonProject
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*PythonProject).Test(&parent, ctx, container)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "TerraformModule":
		switch fnName {
		case "Validate":
			var parent TerraformModule
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return (*TerraformModule).Validate(&parent, ctx, container)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
