// A Dagger module for k8s-homelab CI/CD pipeline
//
// This module provides functions for building, testing, and validating
// the k8s-homelab infrastructure. It is designed to work independently
// of the lab CLI to avoid circular dependencies.
//
// Setup:
//
//	dagger develop  # Generate SDK code in internal/
//	dagger functions  # List available functions
//	dagger call build-cli --source=.  # Build lab CLI
package main

import (
	"context"
	"errors"
	"fmt"
	"runtime"
	"strings"

	"dagger/homelab/internal/dagger"
)

// Homelab is the main Dagger module for k8s-homelab CI/CD
type Homelab struct {
	// DevenvSource holds just the files devenv itself reads: devenv.nix,
	// devenv.yaml, devenv.lock, and cmd/lab (which devenv.yaml imports).
	// Scoped this tightly so a change to a chart or a Python file doesn't
	// invalidate the toolchain container.
	// +private
	DevenvSource *dagger.Directory
}

// New captures the devenv definition the toolchain container is built from.
func New(
	// +defaultPath="/"
	// +ignore=["*", "!devenv.nix", "!devenv.yaml", "!devenv.lock", "!cmd/lab/**"]
	devenvSource *dagger.Directory,
) *Homelab {
	return &Homelab{DevenvSource: devenvSource}
}

// ciContainer returns the toolchain container every check in this module runs in.
func (m *Homelab) ciContainer() *dagger.Container {
	return ciContainer(m.DevenvSource)
}

// FormatNix formats Nix files with alejandra and removes dead code with deadnix.
// Returns a changeset. Use `dagger call format-nix --auto-apply` to apply.
// +generate
func (m *Homelab) FormatNix(
	// +defaultPath="/"
	// +ignore=["*", "!**/*.nix", ".devenv*", ".devenv/**", "devenv.local.*"]
	source *dagger.Directory,
	// +optional
	paths []string,
	// +optional
	container *dagger.Container,
) *dagger.Changeset {
	return m.nixFormat(source, paths, container).Changes(source)
}

// nixFormat runs alejandra and deadnix on source, returning the formatted directory.
//
// Both come from the ci profile rather than `nix-env -iA nixpkgs.*` in the nix
// image, which installed whatever version that image's channel happened to
// carry — a different alejandra than the one devenv.lock pins would reformat
// the tree back and forth between a local run and a CI run.
func (m *Homelab) nixFormat(source *dagger.Directory, paths []string, container *dagger.Container) *dagger.Directory {
	if container == nil {
		container = m.ciContainer()
	}
	container = container.
		WithMountedDirectory("/src", source).
		WithWorkdir("/src")

	targets := []string{"."}
	if len(paths) > 0 {
		targets = paths
	}

	return container.
		WithExec(append([]string{"deadnix", "--edit"}, targets...)).
		WithExec(append([]string{"alejandra"}, targets...)).
		Directory("/src")
}

// LintYaml runs yamllint in strict mode against .yamllint.yaml.
//
// This replaces the yamllint git hook that used to live in devenv.nix, and it
// is a real gate: the previous implementation caught the exec error and
// returned success with a "completed with warnings" string, so `dagger check`
// could never fail on YAML while the local hook blocked the commit.
// +check
func (m *Homelab) LintYaml(ctx context.Context,
	// +defaultPath="/"
	// .pre-commit-config.yaml and .devenv are generated by devenv and
	// gitignored. The config file is a symlink into the nix store, which
	// resolves in a local shell but dangles once copied into a container, so
	// yamllint fails on it with ENOENT rather than a lint error.
	// +ignore=["*", "!**/*.yaml", "!**/*.yml", "!.yamllint.yaml", ".pre-commit-config.yaml", ".devenv*", ".devenv/**", "k8s/**/mixins/vendor/**"]
	source *dagger.Directory,
	// +optional
	paths []string,
	// +optional
	container *dagger.Container,
) (string, error) {
	args := []string{"yamllint", "--config-file", ".yamllint.yaml", "--format", "parsable", "--strict"}
	if len(paths) > 0 {
		args = append(args, paths...)
	} else {
		args = append(args, ".")
	}
	if container == nil {
		container = m.ciContainer()
	}

	out, err := container.
		WithMountedDirectory("/src", source).
		WithWorkdir("/src").
		WithExec(args).
		Stdout(ctx)
	if err != nil {
		if execErr, ok := errors.AsType[*dagger.ExecError](err); ok {
			return "", fmt.Errorf("yamllint failed:\n%s%s", execErr.Stdout, execErr.Stderr)
		}
		return "", fmt.Errorf("yamllint failed: %w\n%s", err, out)
	}

	return "YAML linting passed", nil
}

// ValidateNix runs nix flake check
// +check
func (m *Homelab) ValidateNix(ctx context.Context,
	// +defaultPath="/"
	// +ignore=["*", "!flake.nix", "!flake.lock", "!nix/**/*", "!cmd/lab/flake.nix", "!cmd/lab/flake.lock", "!cmd/lab/default.nix", "!cmd/lab/gomod.json"]
	source *dagger.Directory,
	// +optional
	paths []string, //nolint:unparam // accepted for --paths uniformity across +check functions; flake check always checks the whole tree
) (string, error) {
	_, err := nixContainer().
		WithMountedDirectory("/src", source).
		WithWorkdir("/src").
		WithExec([]string{"nix", "--extra-experimental-features", "nix-command flakes", "flake", "check", "--no-build"}).
		Sync(ctx)
	if err != nil {
		return "", fmt.Errorf("nix flake check failed: %w", err)
	}

	return "Nix flake validation passed", nil
}

// ValidateWoodpecker lints Woodpecker CI pipeline configuration files
// When paths are provided, only matching files are linted
// +check
func (m *Homelab) ValidateWoodpecker(ctx context.Context,
	// +defaultPath="/"
	// +ignore=["*", "!.woodpecker/*.yaml"]
	source *dagger.Directory,
	// +optional
	paths []string,
	// +optional
	container *dagger.Container,
) (string, error) {
	if container == nil {
		container = m.ciContainer()
	}
	container = container.
		WithMountedDirectory("/src", source).
		WithWorkdir("/src")

	if len(paths) > 0 {
		for _, f := range paths {
			container = container.WithExec([]string{"woodpecker-cli", "lint", "--strict", f})
		}
	} else {
		container = container.WithExec([]string{"woodpecker-cli", "lint", "--strict", ".woodpecker/"})
	}

	_, err := container.Sync(ctx)
	if err != nil {
		return "", fmt.Errorf("woodpecker lint failed: %w", err)
	}

	return "Woodpecker validation passed", nil
}

// BuildCli builds the lab CLI binary using Nix
// This ensures the build uses the exact same process as production
// +check
func (m *Homelab) BuildCli(ctx context.Context,
	// +defaultPath="/"
	// +ignore=["*", "!cmd/lab/**/*"]
	source *dagger.Directory,
	// +optional
	paths []string, //nolint:unparam // accepted for --paths uniformity across +check functions; nix build always builds the whole CLI
) (string, error) {
	_, err := nixContainer().
		WithMountedDirectory("/src", source).
		WithWorkdir("/src").
		WithExec([]string{"nix", "--extra-experimental-features", "nix-command flakes", "build", "./cmd/lab", "--print-build-logs"}).
		Sync(ctx)
	if err != nil {
		return "", fmt.Errorf("nix build failed: %w", err)
	}

	return "CLI build passed (Nix)", nil
}

// BuildCliGo builds the lab CLI binary using Go (faster, for testing)
func (m *Homelab) BuildCliGo(ctx context.Context,
	// +defaultPath="/"
	// +ignore=["*", "!cmd/lab/**/*.go", "!cmd/lab/go.mod", "!cmd/lab/go.sum"]
	source *dagger.Directory,
) (string, error) {
	_, err := m.ciContainer().
		WithMountedDirectory("/src", source).
		WithWorkdir("/src/cmd/lab").
		WithExec([]string{"go", "build", "-o", "/out/lab", "."}).
		Sync(ctx)
	if err != nil {
		return "", fmt.Errorf("go build failed: %w", err)
	}

	return "CLI build passed (Go)", nil
}

// Cli returns the built lab CLI binary (using Go for speed)
func (m *Homelab) Cli(ctx context.Context, //nolint:unparam // ctx is idiomatic for Dagger module functions even when the current lazy *dagger.File chain doesn't need it directly
	// +defaultPath="/"
	// +ignore=["*", "!cmd/lab/**/*.go", "!cmd/lab/go.mod", "!cmd/lab/go.sum"]
	source *dagger.Directory,
	platform dagger.Platform,
) *dagger.File {
	// The devenv container only exists for the engine's own platform, so the
	// target platform is honoured by cross-compiling with GOOS/GOARCH rather
	// than by pulling a toolchain image built for it. CGO is already off, so
	// this produces the same static binary either way.
	goos, goarch := splitPlatform(platform)

	return m.ciContainer().
		WithMountedDirectory("/src", source).
		WithWorkdir("/src/cmd/lab").
		WithEnvVariable("CGO_ENABLED", "0").
		WithEnvVariable("GOOS", goos).
		WithEnvVariable("GOARCH", goarch).
		WithExec([]string{"go", "build", "-ldflags", "-s -w", "-o", "/out/lab", "."}).
		File("/out/lab")
}

// splitPlatform turns a Dagger platform ("linux/arm64/v8") into the GOOS and
// GOARCH that name it. The optional variant suffix is dropped: Go selects arm
// variants with GOARM, and none of the platforms this module builds for need it.
func splitPlatform(platform dagger.Platform) (goos, goarch string) {
	parts := strings.Split(string(platform), "/")
	if len(parts) < 2 {
		return runtime.GOOS, runtime.GOARCH
	}
	return parts[0], parts[1]
}

// CliNix returns the built lab CLI binary using Nix
func (m *Homelab) CliNix(ctx context.Context, //nolint:unparam // ctx is idiomatic for Dagger module functions even when the current lazy *dagger.File chain doesn't need it directly
	// +defaultPath="/"
	// +ignore=["*", "!cmd/lab/**/*"]
	source *dagger.Directory,
) *dagger.File {
	return nixContainer().
		WithMountedDirectory("/src", source).
		WithWorkdir("/src").
		WithExec([]string{"nix", "--extra-experimental-features", "nix-command flakes", "build", "./cmd/lab"}).
		File("/src/result/bin/lab")
}

// DevenvContainer builds the devenv nix environment as a minimal "from scratch" container.
// Uses `devenv container copy shell` to produce a minimal nix2container image
// containing only the runtime closure (no build dependencies).
// The resulting container has all dev tools (go, helm, kubectl, etc.) available on PATH.
// The nix store is cached across runs so packages are only built once.
func (m *Homelab) DevenvContainer(
	ws dagger.Workspace,
	// Optional host nix daemon socket for faster builds on NixOS CI hosts.
	// When provided, the host daemon's store is used as a substituter so
	// pre-built packages are fetched rather than rebuilt from source.
	// Note: only works when the host and container share the same platform
	// (e.g. Linux-to-Linux). Does not work with macOS host daemons due to
	// cross-platform path handling differences.
	// +optional
	nixDaemon *dagger.Socket,
	// devenv profiles to activate (https://devenv.sh/profiles/). Defaults to
	// the "ci" profile, which holds exactly the toolchain the check functions
	// need. The "interactive" profile — cluster tooling, the kubeconfig
	// enterShell, the dagger CLI, the git hook — is deliberately not built
	// here; pass it explicitly if you want a full shell to poke at.
	// +optional
	// +default=["ci"]
	profiles []string,
) *dagger.Container {
	source := ws.Directory(".", dagger.WorkspaceDirectoryOpts{
		Gitignore: true,
		Include:   []string{"devenv.*", "cmd/lab/**"},
	})

	return devenvShell(source, nixDaemon, profiles)
}

// devenvShell builds the devenv shell for the given profiles as a minimal
// "from scratch" container.
//
// `devenv container copy shell` produces a nix2container image holding only the
// runtime closure. That image's config carries devenv's own `env.*` settings
// (SSL_CERT_FILE, the UV_PYTHON_* pins, DEVENV_PROFILE) but not PATH, so PATH
// is set here by expanding DEVENV_PROFILE, which contains exactly the packages
// the active profiles declare.
func devenvShell(
	source *dagger.Directory,
	nixDaemon *dagger.Socket,
	profiles []string,
) *dagger.Container {
	builder := devenvContainer().
		WithDirectory("/devenv", source).
		WithWorkdir("/devenv")

	devenvOpts := []string{"--no-tui", "--option", "devenv.warnOnNewVersion:bool", "false"}
	for _, p := range profiles {
		devenvOpts = append(devenvOpts, "--profile", p)
	}
	if nixDaemon != nil {
		builder = builder.
			WithUnixSocket("/nix/var/nix/daemon-socket/socket", nixDaemon)
		// Use the host daemon as a substituter. The "daemon" keyword connects
		// to the socket at the default path (/nix/var/nix/daemon-socket/socket).
		// This works on NixOS CI hosts where architecture matches the container.
		devenvOpts = append(
			devenvOpts,
			"--nix-option", "extra-substituters", "daemon",
			"--nix-option", "require-sigs", "false",
		)
	}

	// Build the minimal shell container and export as docker-archive tarball.
	// devenv container copy uses nix2container + skopeo under the hood.
	// The --registry flag accepts any skopeo transport, including docker-archive.
	// The container name ("shell") is appended to the registry path by devenv,
	// so "docker-archive:/tmp/" produces the file "/tmp/shell".
	tarball := builder.
		WithExec(append([]string{"devenv", "build", "shell"}, devenvOpts...)).
		WithExec(append([]string{"devenv", "container", "copy", "shell", "--registry", "docker-archive:/tmp/"}, devenvOpts...)).
		File("/tmp/shell")

	return dag.Container().Import(tarball).
		WithEnvVariable("PATH", "$DEVENV_PROFILE/bin:/bin", dagger.ContainerWithEnvVariableOpts{Expand: true}).
		WithWorkdir("/src")
}

// DebugDir returns the given dir. Useful for inspecting directory contents for debugging.
func (m *Homelab) DebugDir(ctx context.Context, dir *dagger.Directory) *dagger.Directory {
	return dir
}
