apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:992TzxKucMxPzpYJzGZFdDCbFXNn6QFXWQ==,iv:ZY1VlTJERhz4imiAwpsEp3PtOiRezGowU5tB4oaRJvA=,tag:diX3AGTBKcZ9CPers09L5g==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:RQ6JSfgmqf+5K1EXjPtmTh3XUfCZDbhW4jOLLf84+OqSYL1DD8vJ3g==,iv:84SZ0B1u6FANw1cNATC30ZVu6jYcbBxr6W8+BS8g7pE=,tag:ZHOhFKYPZ7xmp+Z4uleIzw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:JGs2o7axbc5/ItUq,iv:GS95ZKWK577Dnr0FB2I5PNuUxqBMQqozM0okoNvYZKU=,tag:dn9sUk2hoX7s1Qixn6Jm/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ux6jahdtqlrcf3q5n0050vm2sr5qh66m388nfaamct6s643cspdqz8c40f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZllFUzMreTVLUFdxc1cx
            bFRLVHhjcVhzejBYVGZqbXNDTExlZW1HTUVjCkZ6SyswaFREQUpOaEJnOWRHb2VK
            Q0tGaUVXQXV4S2FUTlJJMXZoYW9wVzgKLS0tIDQzVWFXS0xmSmwva3JNVEIwYWhT
            TWVhWCsyT3VqNHFBYkpOZkV1dHpqT28K36SgFV3YkpQ5KEj6i+FhBq8Fn8D+x7f+
            9RW+H4gpV4eSL9L5SQkbTesYyfsLOdqPOn8lhjCIsPRP9GOQAGnB1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T21:15:15Z"
    mac: ENC[AES256_GCM,data:8ylKSAQOKoPh9SQiZ0t8ZUdUaYL3tfvUP1hvQH84vClEqZKJdGiDwS3eVMXPgixuR8lpWmt9TGLaRmaXPLc60LK6GKSoKuBLx/fNIxjBAdwJTwI+YUQhvgoh2rQgMY0shmW7xAZUAm1LjWyn8Wywey0xV5h+PrwSb4P+bH2D58E=,iv:mQASBmY+HRWvyNC9Pv3CLzkLI1FvbyTcgUQdQuU+lEw=,tag:SGOm+p60aPiY8raSKg9O1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
