# Credentials for longhorn to authenticate with smb backup target.
---
apiVersion: v1
kind: Secret
metadata:
  name: cifs-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "csi-driver-smb/smbcreds"
data: {}
