---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-rc1
  namespace: {{ .Release.Namespace }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  # staleReplicaTimeout: "2880" # 48 hours in minutes
  # fromBackup: ""
  # fsType: "ext4"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rc2
  namespace: {{ .Release.Namespace }}
parameters:
  numberOfReplicas: "2"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
