# Credentials for Longhorn to authenticate to the s3proxy backup target.
---
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-s3-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "s3-proxy/s3proxy-credentials"
data:
  AWS_ENDPOINTS: http://s3proxy.s3-proxy.svc.cluster.local
  VIRTUAL_HOSTED_STYLE_ACCESS: "false"
