exemptions:
  - controllerNames:
      - cert-system
    rules:
      - tagNotSpecified
  - controllerNames:
      - cert-system-step-issuer
    rules:
      - privilegeEscalationAllowed
  - controllerNames:
      - step-ca-acme-provisioner
    rules:
      - privilegeEscalationAllowed
      - runAsRootAllowed
  - controllerNames:
      - step-ca-test-connection
    rules:
      - privilegeEscalationAllowed
      - runAsRootAllowed
      - tagNotSpecified
  - controllerNames:
      - step-issuer-bootstrap
    rules:
      - privilegeEscalationAllowed
      - runAsRootAllowed
