exemptions:
  - controllerNames:
      - cert-system
    rules:
      - tagNotSpecified
  - controllerNames:
      - nfs-mtls-cert-sync
    rules:
      - privilegeEscalationAllowed
      - runAsRootAllowed
      - runAsPrivileged
      - hostPIDSet
