apiVersion: v2
name: external-dns
version: 0.0.8
dependencies:
  - name: external-dns
    version: 1.22.0
    repository: https://kubernetes-sigs.github.io/external-dns
  - name: external-dns
    alias: external-dns-internal
    version: 1.22.0
    repository: https://kubernetes-sigs.github.io/external-dns
  - name: external-dns
    alias: external-dns-public-internal
    version: 1.22.0
    repository: https://kubernetes-sigs.github.io/external-dns
