exemptions:
  - controllerNames:
      - external-dns-internal
    rules:
      - privilegeEscalationAllowed
  - controllerNames:
      - external-dns-public-internal
    rules:
      - privilegeEscalationAllowed
