external-dns:
  provider:
    name: cloudflare
  txtOwnerId: homelab
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: value
    - name: DEFAULT_TARGET
      valueFrom:
        configMapKeyRef:
          name: ddns-public-ip
          key: ip
  extraArgs:
    - "--default-targets=$(DEFAULT_TARGET)"
    - "--force-default-targets"
    - "--annotation-filter=traefik.ingress.kubernetes.io/router.entrypoints in (websecurepublic)"
  sources:
    - service
    - ingress
    - gateway-httproute
    - traefik-proxy # Traefik IngressRoute CRDs
  interval: 5m
  triggerLoopOnEvent: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

ddnsUpdater:
  enabled: true
  image:
    repository: alpine/curl
    tag: "8.17.0"
  period: "300" # seconds
  publicIpProvider: https://checkip.amazonaws.com
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
