---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glados-tts-models-pvc
spec:
  storageClassName: longhorn-rc1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glados-tts
  labels:
    app: glados-tts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glados-tts
  template:
    metadata:
      labels:
        app: glados-tts
    spec:
      initContainers:
        - name: model-downloader
          image: "pcloud/gdown"
          command:
            [
              "/bin/sh",
              "-c",
              "if ! ls -1 /models/emb; then gdown https://drive.google.com/uc?id=1nEpr51IEdmCd3IJaPXykhk1oYgpcy1Qn -O /tmp/models.zip; unzip /tmp/models.zip -o -d /models; fi",
            ]
          volumeMounts:
            - name: models
              mountPath: /models
      containers:
        - name: glados-tts
          image: ghcr.io/teekennedy/glados_tts_remote:7c459a5
          ports:
            - containerPort: 8124
          volumeMounts:
            - name: models
              mountPath: /app/models
              readOnly: true
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: glados-tts-models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: glados-tts-service
  namespace: glados-tts
spec:
  selector:
    app: glados-tts
  ports:
    - protocol: TCP
      port: 8124
      targetPort: 8124
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glados-tts
  namespace: glados-tts
  annotations:
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: glados-tts.msng.to
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glados-tts-service
                port:
                  number: 8124
  tls:
    - hosts:
        - glados-tts.msng.to
      secretName: glados-tts-tls
