zot:
  ingress:
    enabled: true
    # If left unset, this defaults to "nginx" which is maddening
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host registry.msng.to
        paths:
          - path: /
    tls:
      - secretName: zot-tls-certificate
        hosts:
          - *host
  # TODO enable auth
  persistence: true
  pvc:
    create: true
    storage: 10Gi
