---
keys:
  # My GPG encryption subkey fingerprint
  - &user_tkennedy FD5B1635F2218760E010601F4A6E1024D7BBE968
  # Age key generated on oxygen
  - &oxygen_age age1ux6jahdtqlrcf3q5n0050vm2sr5qh66m388nfaamct6s643cspdqz8c40f
  # ssh-ed25519 host keys converted to age
  # `nix-shell -p ssh-to-age --run 'ssh-keyscan <host> | grep ssh-ed25519 | ssh-to-age'`
  - &host_borg-0 age134rsuzlwf7fqzl3zluzjmheez6y4x5mmakfsejpjenr6qy3st3rs3rd5l9
  - &host_borg-1 age1sytxxylgnjkdev2qjds6zdwn6ynt73tn4u7lvg27cjdwj97lj4xs75ycyf
  - &host_borg-2 age12uwv74ykhvs45aftm8d4v03ry44jdkt93nmslhktc2u4fq7j7yyqg5zdph

creation_rules:
  - path_regex: hosts/borg-0/secrets\.yaml
    key_groups:
      - pgp:
          - *user_tkennedy
        age:
          - *oxygen_age
          - *host_borg-0
  - path_regex: hosts/borg-1/secrets\.yaml
    key_groups:
      - pgp:
          - *user_tkennedy
        age:
          - *oxygen_age
          - *host_borg-1
  - path_regex: hosts/borg-2/secrets\.yaml
    key_groups:
      - pgp:
          - *user_tkennedy
        age:
          - *oxygen_age
          - *host_borg-2
  - path_regex: modules/k3s/.*\.enc\.yaml
    key_groups:
      - pgp:
          - *user_tkennedy
        age:
          - *oxygen_age
          - *host_borg-0
          - *host_borg-1
          - *host_borg-2
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - *oxygen_age
        pgp:
          - *user_tkennedy
