---
keys:
  # My GPG encryption subkey fingerprint
  - &user_tkennedy FD5B1635F2218760E010601F4A6E1024D7BBE968
  # Age key generated on oxygen
  - &oxygen_age age1ux6jahdtqlrcf3q5n0050vm2sr5qh66m388nfaamct6s643cspdqz8c40f
  # ssh-ed25519 host keys converted to age
  # `nix-shell -p ssh-to-age --run 'ssh-keyscan <host> | grep ssh-ed25519 | ssh-to-age'`
  - &host_borg-0 age134rsuzlwf7fqzl3zluzjmheez6y4x5mmakfsejpjenr6qy3st3rs3rd5l9

creation_rules:
  - path_regex: hosts/borg-0/secrets.ya?ml
    key_groups:
      - pgp:
          - *user_tkennedy
        age:
          - *host_borg-0
  - path_regex: modules/k3s/kubeconfig.enc.yaml
    key_groups:
      - pgp:
          - *user_tkennedy
        age:
          - *host_borg-0
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - *oxygen_age
        pgp:
          - *user_tkennedy
