// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Homelab
func (r *Binding) AsHomelab() *Homelab { // homelab (../../../.dagger/main.go:29:6)
	q := r.query.Select("asHomelab")

	return &Homelab{
		query: q,
	}
}

// Retrieve the binding value, as type HomelabDevenvProject
func (r *Binding) AsHomelabDevenvProject() *HomelabDevenvProject { // homelab (../../../.dagger/devenv.go:49:6)
	q := r.query.Select("asHomelabDevenvProject")

	return &HomelabDevenvProject{
		query: q,
	}
}

// Retrieve the binding value, as type HomelabGoModule
func (r *Binding) AsHomelabGoModule() *HomelabGoModule { // homelab (../../../.dagger/golang.go:37:6)
	q := r.query.Select("asHomelabGoModule")

	return &HomelabGoModule{
		query: q,
	}
}

// Retrieve the binding value, as type HomelabKubernetesIntegrationReport
func (r *Binding) AsHomelabKubernetesIntegrationReport() *HomelabKubernetesIntegrationReport { // homelab (../../../.dagger/integration.go:69:6)
	q := r.query.Select("asHomelabKubernetesIntegrationReport")

	return &HomelabKubernetesIntegrationReport{
		query: q,
	}
}

// Retrieve the binding value, as type HomelabKubernetesIntegrationRun
func (r *Binding) AsHomelabKubernetesIntegrationRun() *HomelabKubernetesIntegrationRun { // homelab (../../../.dagger/integration.go:57:6)
	q := r.query.Select("asHomelabKubernetesIntegrationRun")

	return &HomelabKubernetesIntegrationRun{
		query: q,
	}
}

// Retrieve the binding value, as type HomelabPythonProject
func (r *Binding) AsHomelabPythonProject() *HomelabPythonProject { // homelab (../../../.dagger/python.go:43:6)
	q := r.query.Select("asHomelabPythonProject")

	return &HomelabPythonProject{
		query: q,
	}
}

// Create or update a binding of type HomelabDevenvProject in the environment
func (r *Env) WithHomelabDevenvProjectInput(name string, value *HomelabDevenvProject, description string) *Env { // homelab (../../../.dagger/devenv.go:49:6)
	assertNotNil("value", value)
	q := r.query.Select("withHomelabDevenvProjectInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired HomelabDevenvProject output to be assigned in the environment
func (r *Env) WithHomelabDevenvProjectOutput(name string, description string) *Env { // homelab (../../../.dagger/devenv.go:49:6)
	q := r.query.Select("withHomelabDevenvProjectOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type HomelabGoModule in the environment
func (r *Env) WithHomelabGoModuleInput(name string, value *HomelabGoModule, description string) *Env { // homelab (../../../.dagger/golang.go:37:6)
	assertNotNil("value", value)
	q := r.query.Select("withHomelabGoModuleInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired HomelabGoModule output to be assigned in the environment
func (r *Env) WithHomelabGoModuleOutput(name string, description string) *Env { // homelab (../../../.dagger/golang.go:37:6)
	q := r.query.Select("withHomelabGoModuleOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type Homelab in the environment
func (r *Env) WithHomelabInput(name string, value *Homelab, description string) *Env { // homelab (../../../.dagger/main.go:29:6)
	assertNotNil("value", value)
	q := r.query.Select("withHomelabInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type HomelabKubernetesIntegrationReport in the environment
func (r *Env) WithHomelabKubernetesIntegrationReportInput(name string, value *HomelabKubernetesIntegrationReport, description string) *Env { // homelab (../../../.dagger/integration.go:69:6)
	assertNotNil("value", value)
	q := r.query.Select("withHomelabKubernetesIntegrationReportInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired HomelabKubernetesIntegrationReport output to be assigned in the environment
func (r *Env) WithHomelabKubernetesIntegrationReportOutput(name string, description string) *Env { // homelab (../../../.dagger/integration.go:69:6)
	q := r.query.Select("withHomelabKubernetesIntegrationReportOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type HomelabKubernetesIntegrationRun in the environment
func (r *Env) WithHomelabKubernetesIntegrationRunInput(name string, value *HomelabKubernetesIntegrationRun, description string) *Env { // homelab (../../../.dagger/integration.go:57:6)
	assertNotNil("value", value)
	q := r.query.Select("withHomelabKubernetesIntegrationRunInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired HomelabKubernetesIntegrationRun output to be assigned in the environment
func (r *Env) WithHomelabKubernetesIntegrationRunOutput(name string, description string) *Env { // homelab (../../../.dagger/integration.go:57:6)
	q := r.query.Select("withHomelabKubernetesIntegrationRunOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Homelab output to be assigned in the environment
func (r *Env) WithHomelabOutput(name string, description string) *Env { // homelab (../../../.dagger/main.go:29:6)
	q := r.query.Select("withHomelabOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type HomelabPythonProject in the environment
func (r *Env) WithHomelabPythonProjectInput(name string, value *HomelabPythonProject, description string) *Env { // homelab (../../../.dagger/python.go:43:6)
	assertNotNil("value", value)
	q := r.query.Select("withHomelabPythonProjectInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired HomelabPythonProject output to be assigned in the environment
func (r *Env) WithHomelabPythonProjectOutput(name string, description string) *Env { // homelab (../../../.dagger/python.go:43:6)
	q := r.query.Select("withHomelabPythonProjectOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Homelab is the main Dagger module for k8s-homelab CI/CD
type Homelab struct { // homelab (../../../.dagger/main.go:29:6)
	query *querybuilder.Selection

	buildCli                  *string
	buildCliGo                *string
	buildHelmfile             *string
	id                        *ID
	lintHelmfile              *string
	lintTerraform             *string
	lintYaml                  *string
	testGo                    *string
	testKubernetesIntegration *string
	testPython                *string
	validateHelmfile          *string
	validateKubeconform       *string
	validateNix               *string
	validateNixBuildMetrics   *string
	validatePolaris           *string
	validateTerraform         *string
	validateWoodpecker        *string
	verifyCacheGranularity    *string
}

func (r *Homelab) WithGraphQLQuery(q *querybuilder.Selection) *Homelab {
	return &Homelab{
		query: q,
	}
}

// HomelabBuildCliOpts contains options for Homelab.BuildCli
type HomelabBuildCliOpts struct {
	Source *Directory // homelab (../../../.dagger/main.go:251:2)

	Paths []string // homelab (../../../.dagger/main.go:253:2)
}

// BuildCli builds the lab CLI binary using Nix
// This ensures the build uses the exact same process as production
func (r *Homelab) BuildCli(ctx context.Context, opts ...HomelabBuildCliOpts) (string, error) { // homelab (../../../.dagger/main.go:248:1)
	if r.buildCli != nil {
		return *r.buildCli, nil
	}
	q := r.query.Select("buildCli")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabBuildCliGoOpts contains options for Homelab.BuildCliGo
type HomelabBuildCliGoOpts struct {
	Source *Directory // homelab (../../../.dagger/main.go:271:2)
}

// BuildCliGo builds the lab CLI binary using Go (faster, for testing)
func (r *Homelab) BuildCliGo(ctx context.Context, opts ...HomelabBuildCliGoOpts) (string, error) { // homelab (../../../.dagger/main.go:268:1)
	if r.buildCliGo != nil {
		return *r.buildCliGo, nil
	}
	q := r.query.Select("buildCliGo")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabBuildHelmfileOpts contains options for Homelab.BuildHelmfile
type HomelabBuildHelmfileOpts struct {
	//
	// charts/*.tgz are built dependencies; they are gitignored, so leaving them
	// out makes a local run resolve dependencies the way a clean checkout does.
	//
	Source *Directory // homelab (../../../.dagger/helmfile.go:198:2)
	//
	// Helmfile environments to render with.
	//
	//
	// Default: ["production"]
	Environments []string // homelab (../../../.dagger/helmfile.go:202:2)

	Paths []string // homelab (../../../.dagger/helmfile.go:204:2)

	Container *Container // homelab (../../../.dagger/helmfile.go:206:2)
}

// BuildHelmfile renders every chart with `helmfile template`, once per
// environment. Each release is rendered from a scoped source directory so that
// a change to one chart doesn't invalidate the cache for the others.
// When paths are provided, only charts matching the paths are rendered.
func (r *Homelab) BuildHelmfile(ctx context.Context, opts ...HomelabBuildHelmfileOpts) (string, error) { // homelab (../../../.dagger/helmfile.go:193:1)
	if r.buildHelmfile != nil {
		return *r.buildHelmfile, nil
	}
	q := r.query.Select("buildHelmfile")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `environments` optional argument
		if !querybuilder.IsZeroValue(opts[i].Environments) {
			q = q.Arg("environments", opts[i].Environments)
		}
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabCliOpts contains options for Homelab.Cli
type HomelabCliOpts struct {
	Source *Directory // homelab (../../../.dagger/main.go:289:2)
}

// Cli returns the built lab CLI binary (using Go for speed)
func (r *Homelab) Cli(platform Platform, opts ...HomelabCliOpts) *File { // homelab (../../../.dagger/main.go:286:1)
	q := r.query.Select("cli")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}
	q = q.Arg("platform", platform)

	return &File{
		query: q,
	}
}

// HomelabCliNixOpts contains options for Homelab.CliNix
type HomelabCliNixOpts struct {
	Source *Directory // homelab (../../../.dagger/main.go:323:2)
}

// CliNix returns the built lab CLI binary using Nix
func (r *Homelab) CliNix(opts ...HomelabCliNixOpts) *File { // homelab (../../../.dagger/main.go:320:1)
	q := r.query.Select("cliNix")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}

	return &File{
		query: q,
	}
}

// DebugDir returns the given dir. Useful for inspecting directory contents for debugging.
func (r *Homelab) DebugDir(dir *Directory) *Directory { // homelab (../../../.dagger/main.go:414:1)
	assertNotNil("dir", dir)
	q := r.query.Select("debugDir")
	q = q.Arg("dir", dir)

	return &Directory{
		query: q,
	}
}

// HomelabDevenvContainerOpts contains options for Homelab.DevenvContainer
type HomelabDevenvContainerOpts struct {
	Ws *Workspace // homelab (../../../.dagger/main.go:338:2)
	//
	// Optional host nix daemon socket for faster builds on NixOS CI hosts.
	// When provided, the host daemon's store is used as a substituter so
	// pre-built packages are fetched rather than rebuilt from source.
	// Note: only works when the host and container share the same platform
	// (e.g. Linux-to-Linux). Does not work with macOS host daemons due to
	// cross-platform path handling differences.
	//
	NixDaemon *Socket // homelab (../../../.dagger/main.go:346:2)
	//
	// devenv profiles to activate (https://devenv.sh/profiles/). Defaults to
	// the "ci" profile, which holds exactly the toolchain the check functions
	// need. The "interactive" profile — cluster tooling, the kubeconfig
	// enterShell, the dagger CLI, the git hook — is deliberately not built
	// here; pass it explicitly if you want a full shell to poke at.
	//
	//
	// Default: ["ci"]
	Profiles []string // homelab (../../../.dagger/main.go:354:2)
}

// DevenvContainer builds the devenv nix environment as a minimal "from scratch" container.
// Uses `devenv container copy shell` to produce a minimal nix2container image
// containing only the runtime closure (no build dependencies).
// The resulting container has all dev tools (go, helm, kubectl, etc.) available on PATH.
// The nix store is cached across runs so packages are only built once.
func (r *Homelab) DevenvContainer(opts ...HomelabDevenvContainerOpts) *Container { // homelab (../../../.dagger/main.go:337:1)
	q := r.query.Select("devenvContainer")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
		// `nixDaemon` optional argument
		if !querybuilder.IsZeroValue(opts[i].NixDaemon) {
			q = q.Arg("nixDaemon", opts[i].NixDaemon)
		}
		// `profiles` optional argument
		if !querybuilder.IsZeroValue(opts[i].Profiles) {
			q = q.Arg("profiles", opts[i].Profiles)
		}
	}

	return &Container{
		query: q,
	}
}

// HomelabDevenvProjectsOpts contains options for Homelab.DevenvProjects
type HomelabDevenvProjectsOpts struct {
	Source *Directory // homelab (../../../.dagger/devenv.go:65:2)
}

// DevenvProjects returns all discovered devenv projects with scoped source directories.
// The +ignore list mirrors DevenvContainer's file selection: devenv.yaml/
// devenv.nix/devenv.lock are what devenv itself reads, plus cmd/lab because
// the root project's devenv.yaml imports it. This doesn't generalize to a
// future devenv project that imports some other path.
func (r *Homelab) DevenvProjects(ctx context.Context, opts ...HomelabDevenvProjectsOpts) ([]HomelabDevenvProject, error) { // homelab (../../../.dagger/devenv.go:61:1)
	q := r.query.Select("devenvProjects")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}

	q = q.Select("id")

	type devenvProjects struct {
		Id ID
	}

	convert := func(fields []devenvProjects) []HomelabDevenvProject {
		out := []HomelabDevenvProject{}

		for i := range fields {
			val := HomelabDevenvProject{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "HomelabDevenvProject")
			out = append(out, val)
		}

		return out
	}
	var response []devenvProjects

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// HomelabExportCueOpts contains options for Homelab.ExportCue
type HomelabExportCueOpts struct {
	Source *Directory // homelab (../../../.dagger/cue.go:77:2)

	Container *Container // homelab (../../../.dagger/cue.go:79:2)
}

// ExportCue exports each CUE environment to config/gen/<env>/env.json.
// Environments are discovered dynamically from the package's exported top-level values.
func (r *Homelab) ExportCue(opts ...HomelabExportCueOpts) *Changeset { // homelab (../../../.dagger/cue.go:73:1)
	q := r.query.Select("exportCue")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Changeset{
		query: q,
	}
}

// HomelabFixCueOpts contains options for Homelab.FixCue
type HomelabFixCueOpts struct {
	Source *Directory // homelab (../../../.dagger/cue.go:45:2)

	Container *Container // homelab (../../../.dagger/cue.go:47:2)
}

// FixCue upgrades CUE syntax to the current language version using cue fix.
func (r *Homelab) FixCue(opts ...HomelabFixCueOpts) *Changeset { // homelab (../../../.dagger/cue.go:42:1)
	q := r.query.Select("fixCue")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Changeset{
		query: q,
	}
}

// HomelabFormatCueOpts contains options for Homelab.FormatCue
type HomelabFormatCueOpts struct {
	Source *Directory // homelab (../../../.dagger/cue.go:30:2)

	Container *Container // homelab (../../../.dagger/cue.go:32:2)
}

// FormatCue formats CUE files with cue fmt.
func (r *Homelab) FormatCue(opts ...HomelabFormatCueOpts) *Changeset { // homelab (../../../.dagger/cue.go:27:1)
	q := r.query.Select("formatCue")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Changeset{
		query: q,
	}
}

// HomelabFormatNixOpts contains options for Homelab.FormatNix
type HomelabFormatNixOpts struct {
	Source *Directory // homelab (../../../.dagger/main.go:64:2)

	Paths []string // homelab (../../../.dagger/main.go:66:2)

	Container *Container // homelab (../../../.dagger/main.go:68:2)
}

// FormatNix formats Nix files with alejandra and removes dead code with deadnix.
// Returns a changeset. Use `dagger call format-nix --auto-apply` to apply.
func (r *Homelab) FormatNix(opts ...HomelabFormatNixOpts) *Changeset { // homelab (../../../.dagger/main.go:61:1)
	q := r.query.Select("formatNix")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Changeset{
		query: q,
	}
}

// HomelabFormatPythonOpts contains options for Homelab.FormatPython
type HomelabFormatPythonOpts struct {
	Source *Directory // homelab (../../../.dagger/python.go:236:2)

	Paths []string // homelab (../../../.dagger/python.go:238:2)

	Container *Container // homelab (../../../.dagger/python.go:240:2)
}

// FormatPython formats Python files with black across all discovered projects.
// Returns a changeset. Use `dagger call format-python --auto-apply` to apply.
func (r *Homelab) FormatPython(opts ...HomelabFormatPythonOpts) *Changeset { // homelab (../../../.dagger/python.go:232:1)
	q := r.query.Select("formatPython")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Changeset{
		query: q,
	}
}

// HomelabFormatTerraformOpts contains options for Homelab.FormatTerraform
type HomelabFormatTerraformOpts struct {
	Source *Directory // homelab (../../../.dagger/terraform.go:163:2)

	Container *Container // homelab (../../../.dagger/terraform.go:165:2)
}

// FormatTerraform formats Terraform/OpenTofu files with `tofu fmt`.
//
// `tofu fmt -recursive` is run once over the whole terraform/ tree rather than
// per module, because unlike validate it needs no per-module init and the
// modules already share a single source directory.
// Returns a changeset. Use `dagger generate format-terraform --auto-apply` to apply.
func (r *Homelab) FormatTerraform(opts ...HomelabFormatTerraformOpts) *Changeset { // homelab (../../../.dagger/terraform.go:160:1)
	q := r.query.Select("formatTerraform")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Changeset{
		query: q,
	}
}

// HomelabGoModulesOpts contains options for Homelab.GoModules
type HomelabGoModulesOpts struct {
	Source *Directory // homelab (../../../.dagger/golang.go:53:2)
}

// GoModules returns all discovered Go modules with scoped source directories.
// Each module's Source is a subdirectory of the +defaultPath source, so
// Directory IDs are stable across sessions and cache independently.
func (r *Homelab) GoModules(ctx context.Context, opts ...HomelabGoModulesOpts) ([]HomelabGoModule, error) { // homelab (../../../.dagger/golang.go:49:1)
	q := r.query.Select("goModules")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}

	q = q.Select("id")

	type goModules struct {
		Id ID
	}

	convert := func(fields []goModules) []HomelabGoModule {
		out := []HomelabGoModule{}

		for i := range fields {
			val := HomelabGoModule{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "HomelabGoModule")
			out = append(out, val)
		}

		return out
	}
	var response []goModules

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// A unique identifier for this Homelab.
func (r *Homelab) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Homelab) XXX_GraphQLType() string {
	return "Homelab"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Homelab) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Homelab) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Homelab) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Homelab) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Homelab{query: selectNode(dag.query, id, "Homelab")}
	return nil
}

// HomelabKubernetesIntegrationReportsOpts contains options for Homelab.KubernetesIntegrationReports
type HomelabKubernetesIntegrationReportsOpts struct {
	Source *Directory // homelab (../../../.dagger/integration.go:135:2)

	Releases []string // homelab (../../../.dagger/integration.go:137:2)

	RepeatSync bool // homelab (../../../.dagger/integration.go:139:2)

	Container *Container // homelab (../../../.dagger/integration.go:141:2)
}

// KubernetesIntegrationReports runs the same workflow and returns the JUnit XML
// reports, one file per release:
//
//	dagger call kubernetes-integration-reports export --path=./reports
//
// A failing test is not an error here — getting the report out is the point —
// but a cluster that never came up, or a release that never became healthy,
// still is.
func (r *Homelab) KubernetesIntegrationReports(opts ...HomelabKubernetesIntegrationReportsOpts) *Directory { // homelab (../../../.dagger/integration.go:132:1)
	q := r.query.Select("kubernetesIntegrationReports")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `releases` optional argument
		if !querybuilder.IsZeroValue(opts[i].Releases) {
			q = q.Arg("releases", opts[i].Releases)
		}
		// `repeatSync` optional argument
		if !querybuilder.IsZeroValue(opts[i].RepeatSync) {
			q = q.Arg("repeatSync", opts[i].RepeatSync)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Directory{
		query: q,
	}
}

// HomelabLintGoOpts contains options for Homelab.LintGo
type HomelabLintGoOpts struct {
	Source *Directory // homelab (../../../.dagger/golang.go:105:2)

	Container *Container // homelab (../../../.dagger/golang.go:107:2)
}

// LintGo tidies go.mod/go.sum and applies golangci-lint's autofixes (including
// formatting) across all discovered Go modules.
// Fails if issues remain that --fix cannot resolve (e.g. cyclop, gosec).
// Returns a changeset. Use `dagger call lint-go --auto-apply` to apply.
func (r *Homelab) LintGo(opts ...HomelabLintGoOpts) *Changeset { // homelab (../../../.dagger/golang.go:101:1)
	q := r.query.Select("lintGo")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Changeset{
		query: q,
	}
}

// HomelabLintHelmfileOpts contains options for Homelab.LintHelmfile
type HomelabLintHelmfileOpts struct {
	//
	// Only Chart.yaml is needed from k8s/, to know which charts exist.
	//
	Source *Directory // homelab (../../../.dagger/helmfile.go:259:2)
	//
	// Helmfile environments to lint.
	//
	//
	// Default: ["production"]
	Environments []string // homelab (../../../.dagger/helmfile.go:263:2)

	Container *Container // homelab (../../../.dagger/helmfile.go:265:2)
}

// LintHelmfile checks the helmfile state itself, once per environment: that it
// renders (`helmfile build`), and that its releases, the chart directories and
// the environment's app list agree with each other.
func (r *Homelab) LintHelmfile(ctx context.Context, opts ...HomelabLintHelmfileOpts) (string, error) { // homelab (../../../.dagger/helmfile.go:255:1)
	if r.lintHelmfile != nil {
		return *r.lintHelmfile, nil
	}
	q := r.query.Select("lintHelmfile")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `environments` optional argument
		if !querybuilder.IsZeroValue(opts[i].Environments) {
			q = q.Arg("environments", opts[i].Environments)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabLintTerraformOpts contains options for Homelab.LintTerraform
type HomelabLintTerraformOpts struct {
	Source *Directory // homelab (../../../.dagger/terraform.go:222:2)

	Container *Container // homelab (../../../.dagger/terraform.go:224:2)
}

// LintTerraform runs trivy config against the Terraform/OpenTofu tree to catch
// misconfigurations (unencrypted resources, over-permissive IAM, etc.).
//
// Trivy supersedes tfsec (the two tools' checks now live in the same
// aquasecurity org, and tfsec is in maintenance-only mode), so this uses
// trivy rather than tfsec directly. --skip-check-update and --skip-version-check
// keep it network-independent and quiet.
func (r *Homelab) LintTerraform(ctx context.Context, opts ...HomelabLintTerraformOpts) (string, error) { // homelab (../../../.dagger/terraform.go:219:1)
	if r.lintTerraform != nil {
		return *r.lintTerraform, nil
	}
	q := r.query.Select("lintTerraform")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabLintYamlOpts contains options for Homelab.LintYaml
type HomelabLintYamlOpts struct {
	//
	// .pre-commit-config.yaml and .devenv are generated by devenv and
	// gitignored. The config file is a symlink into the nix store, which
	// resolves in a local shell but dangles once copied into a container, so
	// yamllint fails on it with ENOENT rather than a lint error.
	//
	Source *Directory // homelab (../../../.dagger/main.go:112:2)

	Paths []string // homelab (../../../.dagger/main.go:114:2)

	Container *Container // homelab (../../../.dagger/main.go:116:2)
}

// LintYaml runs yamllint in strict mode against .yamllint.yaml.
//
// This replaces the yamllint git hook that used to live in devenv.nix, and it
// is a real gate: the previous implementation caught the exec error and
// returned success with a "completed with warnings" string, so `dagger check`
// could never fail on YAML while the local hook blocked the commit.
func (r *Homelab) LintYaml(ctx context.Context, opts ...HomelabLintYamlOpts) (string, error) { // homelab (../../../.dagger/main.go:105:1)
	if r.lintYaml != nil {
		return *r.lintYaml, nil
	}
	q := r.query.Select("lintYaml")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabLockTerraformOpts contains options for Homelab.LockTerraform
type HomelabLockTerraformOpts struct {
	Source *Directory // homelab (../../../.dagger/terraform.go:121:2)

	Container *Container // homelab (../../../.dagger/terraform.go:123:2)
	//
	// platforms to compute provider hashes for.
	//
	//
	// Default: ["linux_arm64","linux_amd64","darwin_arm64"]
	Platforms []string // homelab (../../../.dagger/terraform.go:127:2)
}

// LockTerraform runs tofu providers lock for all Terraform/OpenTofu modules.
//
// Unlike `tofu init`, `tofu providers lock` computes provider hashes for the
// given platforms deterministically, regardless of the platform it runs on.
// This keeps .terraform.lock.hcl stable across different machines, which
// `tofu init` cannot guarantee since it only records hashes for the host
// platform it happens to run on.
//
// Returns a changeset. Use `dagger generate lock-terraform --auto-apply` to apply
// lockfile changes produced by provider locking.
func (r *Homelab) LockTerraform(opts ...HomelabLockTerraformOpts) *Changeset { // homelab (../../../.dagger/terraform.go:117:1)
	q := r.query.Select("lockTerraform")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
		// `platforms` optional argument
		if !querybuilder.IsZeroValue(opts[i].Platforms) {
			q = q.Arg("platforms", opts[i].Platforms)
		}
	}

	return &Changeset{
		query: q,
	}
}

// HomelabPythonProjectsOpts contains options for Homelab.PythonProjects
type HomelabPythonProjectsOpts struct {
	Source *Directory // homelab (../../../.dagger/python.go:93:2)
}

// PythonProjects returns all discovered Python projects with scoped source
// directories.
func (r *Homelab) PythonProjects(ctx context.Context, opts ...HomelabPythonProjectsOpts) ([]HomelabPythonProject, error) { // homelab (../../../.dagger/python.go:89:1)
	q := r.query.Select("pythonProjects")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}

	q = q.Select("id")

	type pythonProjects struct {
		Id ID
	}

	convert := func(fields []pythonProjects) []HomelabPythonProject {
		out := []HomelabPythonProject{}

		for i := range fields {
			val := HomelabPythonProject{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "HomelabPythonProject")
			out = append(out, val)
		}

		return out
	}
	var response []pythonProjects

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// HomelabRunKubernetesIntegrationOpts contains options for Homelab.RunKubernetesIntegration
type HomelabRunKubernetesIntegrationOpts struct {
	RepeatSync bool // homelab (../../../.dagger/integration.go:228:2)

	Container *Container // homelab (../../../.dagger/integration.go:230:2)
}

// RunKubernetesIntegration is the cached half of the workflow, and what
// TestKubernetesIntegration and KubernetesIntegrationReports call: plan, create,
// deploy, wait, prove, test, destroy. It is exported only so that they can reach
// it through the module's own API, which is what lets Dagger cache it on its own
// arguments; invoke those two instead.
//
// source is the scoped layout scopedIntegrationSource builds — the state file,
// the ephemeral values and the chosen releases' charts — rather than the whole
// repo. That is the point: the caller's `source` covers everything under k8s/, so
// a change to any chart re-runs the caller, but only a change to something this
// run deploys changes this argument.
func (r *Homelab) RunKubernetesIntegration(source *Directory, releases []string, opts ...HomelabRunKubernetesIntegrationOpts) *HomelabKubernetesIntegrationRun { // homelab (../../../.dagger/integration.go:224:1)
	assertNotNil("source", source)
	q := r.query.Select("runKubernetesIntegration")
	for i := len(opts) - 1; i >= 0; i-- {
		// `repeatSync` optional argument
		if !querybuilder.IsZeroValue(opts[i].RepeatSync) {
			q = q.Arg("repeatSync", opts[i].RepeatSync)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}
	q = q.Arg("source", source)
	q = q.Arg("releases", releases)

	return &HomelabKubernetesIntegrationRun{
		query: q,
	}
}

// HomelabTestGoOpts contains options for Homelab.TestGo
type HomelabTestGoOpts struct {
	//
	// scripts/*.sh is here because .dagger/gomodhash.go go:embeds it; without
	// it that module does not build and `go test` fails at setup.
	//
	Source *Directory // homelab (../../../.dagger/golang.go:192:2)

	Container *Container // homelab (../../../.dagger/golang.go:194:2)
}

// TestGo runs Go tests for all discovered Go modules.
// Each module is tested with a scoped source directory so that changes
// in one module don't invalidate the BuildKit cache for other modules.
func (r *Homelab) TestGo(ctx context.Context, opts ...HomelabTestGoOpts) (string, error) { // homelab (../../../.dagger/golang.go:186:1)
	if r.testGo != nil {
		return *r.testGo, nil
	}
	q := r.query.Select("testGo")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabTestKubernetesIntegrationOpts contains options for Homelab.TestKubernetesIntegration
type HomelabTestKubernetesIntegrationOpts struct {
	Source *Directory // homelab (../../../.dagger/integration.go:93:2)
	//
	// Helmfile releases to deploy and test, narrowing the set the ephemeral
	// environment enables. Empty means all of them.
	//
	Releases []string // homelab (../../../.dagger/integration.go:97:2)
	//
	// Sync twice before testing, to check that re-syncing a cluster that
	// already has the releases on it succeeds.
	//
	RepeatSync bool // homelab (../../../.dagger/integration.go:101:2)

	Container *Container // homelab (../../../.dagger/integration.go:103:2)
}

// TestKubernetesIntegration deploys releases to a throwaway k3s cluster and runs
// their Kubernetes integration tests against it.
//
// Deliberately not a `+check`: it needs an engine that allows privileged execs,
// and a PR can change both this code and the tests it runs. Invoke it explicitly:
//
//	dagger call test-kubernetes-integration
//	dagger call test-kubernetes-integration --releases=reflector
//
// The result is cached like any function call: the same source and arguments
// return the earlier verdict without starting a cluster. The cluster is created,
// used and destroyed inside this call. Nothing reads,
// writes or merges a kubeconfig outside the engine, and no host context
// changes. See "Kubernetes integration tests" in README.md for prerequisites.
func (r *Homelab) TestKubernetesIntegration(ctx context.Context, opts ...HomelabTestKubernetesIntegrationOpts) (string, error) { // homelab (../../../.dagger/integration.go:90:1)
	if r.testKubernetesIntegration != nil {
		return *r.testKubernetesIntegration, nil
	}
	q := r.query.Select("testKubernetesIntegration")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `releases` optional argument
		if !querybuilder.IsZeroValue(opts[i].Releases) {
			q = q.Arg("releases", opts[i].Releases)
		}
		// `repeatSync` optional argument
		if !querybuilder.IsZeroValue(opts[i].RepeatSync) {
			q = q.Arg("repeatSync", opts[i].RepeatSync)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabTestPythonOpts contains options for Homelab.TestPython
type HomelabTestPythonOpts struct {
	Source *Directory // homelab (../../../.dagger/python.go:273:2)

	Paths []string // homelab (../../../.dagger/python.go:275:2)

	Container *Container // homelab (../../../.dagger/python.go:277:2)
}

// TestPython runs pytest for all discovered Python projects.
func (r *Homelab) TestPython(ctx context.Context, opts ...HomelabTestPythonOpts) (string, error) { // homelab (../../../.dagger/python.go:270:1)
	if r.testPython != nil {
		return *r.testPython, nil
	}
	q := r.query.Select("testPython")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabTrimCueOpts contains options for Homelab.TrimCue
type HomelabTrimCueOpts struct {
	Source *Directory // homelab (../../../.dagger/cue.go:60:2)

	Container *Container // homelab (../../../.dagger/cue.go:62:2)
}

// TrimCue removes redundant values implied by schema constraints using cue trim.
func (r *Homelab) TrimCue(opts ...HomelabTrimCueOpts) *Changeset { // homelab (../../../.dagger/cue.go:57:1)
	q := r.query.Select("trimCue")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Changeset{
		query: q,
	}
}

// HomelabUpdateDevenvOpts contains options for Homelab.UpdateDevenv
type HomelabUpdateDevenvOpts struct {
	Source *Directory // homelab (../../../.dagger/devenv.go:113:2)
}

// UpdateDevenv runs `devenv update` for every discovered devenv project and
// returns the combined changeset. Each project runs in its own container
// with only its own scoped source mounted, so a lock change in one project
// doesn't invalidate the cache for the others.
//
// Deliberately not tagged +generate. +generate implies a reproducible step
// that recomputes a value from other checked-in inputs (like
// UpdateGoVendorHash). devenv update instead fetches whatever the latest
// commit happens to be for each input right now, so running it twice in a
// row can produce different output — it belongs to CI as a scheduled
// "refresh" step, not as generated code to keep in sync.
// Use `dagger call update-devenv --auto-apply` to apply.
func (r *Homelab) UpdateDevenv(opts ...HomelabUpdateDevenvOpts) *Changeset { // homelab (../../../.dagger/devenv.go:109:1)
	q := r.query.Select("updateDevenv")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}

	return &Changeset{
		query: q,
	}
}

// HomelabUpdateGoVendorHashOpts contains options for Homelab.UpdateGoVendorHash
type HomelabUpdateGoVendorHashOpts struct {
	//
	// buildGoModule vendors only the packages the source actually imports, so
	// the whole module directory is needed to produce the right hash.
	//
	Source *Directory // homelab (../../../.dagger/gomodhash.go:34:2)
}

// UpdateGoVendorHash recomputes the nix buildGoModule vendorHash for cmd/lab
// and writes it to cmd/lab/gomod.json. Run this whenever a Go dependency of
// the lab CLI changes, otherwise the nix (and therefore devenv) build fails
// with a fixed-output hash mismatch.
// Returns a changeset. Use `dagger call update-go-vendor-hash --auto-apply` to apply.
func (r *Homelab) UpdateGoVendorHash(opts ...HomelabUpdateGoVendorHashOpts) *Changeset { // homelab (../../../.dagger/gomodhash.go:28:1)
	q := r.query.Select("updateGoVendorHash")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
	}

	return &Changeset{
		query: q,
	}
}

// HomelabValidateHelmfileOpts contains options for Homelab.ValidateHelmfile
type HomelabValidateHelmfileOpts struct {
	Source *Directory // homelab (../../../.dagger/helmfile.go:228:2)
	//
	// Helmfile environments to lint with.
	//
	//
	// Default: ["production"]
	Environments []string // homelab (../../../.dagger/helmfile.go:232:2)

	Paths []string // homelab (../../../.dagger/helmfile.go:234:2)

	Container *Container // homelab (../../../.dagger/helmfile.go:236:2)
}

// ValidateHelmfile runs `helmfile lint` on every chart, once per environment.
// It lints each chart with the values helmfile would deploy it with.
// When paths are provided, only charts matching the paths are linted.
func (r *Homelab) ValidateHelmfile(ctx context.Context, opts ...HomelabValidateHelmfileOpts) (string, error) { // homelab (../../../.dagger/helmfile.go:225:1)
	if r.validateHelmfile != nil {
		return *r.validateHelmfile, nil
	}
	q := r.query.Select("validateHelmfile")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `environments` optional argument
		if !querybuilder.IsZeroValue(opts[i].Environments) {
			q = q.Arg("environments", opts[i].Environments)
		}
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabValidateKubeconformOpts contains options for Homelab.ValidateKubeconform
type HomelabValidateKubeconformOpts struct {
	Source *Directory // homelab (../../../.dagger/kubernetes.go:157:2)
	//
	// Helmfile environments to render with.
	//
	//
	// Default: ["production"]
	Environments []string // homelab (../../../.dagger/kubernetes.go:161:2)

	Paths []string // homelab (../../../.dagger/kubernetes.go:163:2)

	Container *Container // homelab (../../../.dagger/kubernetes.go:165:2)
}

// ValidateKubeconform runs kubeconform in strict mode across all Helm charts,
// once per environment, on the manifests helmfile renders.
// When paths are provided, only matching charts are validated.
func (r *Homelab) ValidateKubeconform(ctx context.Context, opts ...HomelabValidateKubeconformOpts) (string, error) { // homelab (../../../.dagger/kubernetes.go:154:1)
	if r.validateKubeconform != nil {
		return *r.validateKubeconform, nil
	}
	q := r.query.Select("validateKubeconform")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `environments` optional argument
		if !querybuilder.IsZeroValue(opts[i].Environments) {
			q = q.Arg("environments", opts[i].Environments)
		}
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabValidateNixOpts contains options for Homelab.ValidateNix
type HomelabValidateNixOpts struct {
	Source *Directory // homelab (../../../.dagger/main.go:148:2)

	Container *Container // homelab (../../../.dagger/main.go:150:2)
}

// ValidateNix runs nix flake check
func (r *Homelab) ValidateNix(ctx context.Context, opts ...HomelabValidateNixOpts) (string, error) { // homelab (../../../.dagger/main.go:145:1)
	if r.validateNix != nil {
		return *r.validateNix, nil
	}
	q := r.query.Select("validateNix")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabValidateNixBuildMetricsOpts contains options for Homelab.ValidateNixBuildMetrics
type HomelabValidateNixBuildMetricsOpts struct {
	Source *Directory // homelab (../../../.dagger/main.go:175:2)

	Container *Container // homelab (../../../.dagger/main.go:177:2)
}

// ValidateNixBuildMetrics runs a real Nix build through the selfupdate metrics
// parser's Python test suite, so a Nix upgrade that changes the internal-json
// event stream (NixOS/nix#13935) is caught here instead of only on a host.
func (r *Homelab) ValidateNixBuildMetrics(ctx context.Context, opts ...HomelabValidateNixBuildMetricsOpts) (string, error) { // homelab (../../../.dagger/main.go:172:1)
	if r.validateNixBuildMetrics != nil {
		return *r.validateNixBuildMetrics, nil
	}
	q := r.query.Select("validateNixBuildMetrics")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabValidatePolarisOpts contains options for Homelab.ValidatePolaris
type HomelabValidatePolarisOpts struct {
	Source *Directory // homelab (../../../.dagger/kubernetes.go:127:2)
	//
	// Helmfile environments to render with.
	//
	//
	// Default: ["production"]
	Environments []string // homelab (../../../.dagger/kubernetes.go:131:2)

	Paths []string // homelab (../../../.dagger/kubernetes.go:133:2)

	Container *Container // homelab (../../../.dagger/kubernetes.go:135:2)
}

// ValidatePolaris runs Polaris audit across all Helm charts, once per
// environment, on the manifests helmfile renders.
// When paths are provided, only matching charts are validated.
func (r *Homelab) ValidatePolaris(ctx context.Context, opts ...HomelabValidatePolarisOpts) (string, error) { // homelab (../../../.dagger/kubernetes.go:124:1)
	if r.validatePolaris != nil {
		return *r.validatePolaris, nil
	}
	q := r.query.Select("validatePolaris")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `environments` optional argument
		if !querybuilder.IsZeroValue(opts[i].Environments) {
			q = q.Arg("environments", opts[i].Environments)
		}
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabValidateTerraformOpts contains options for Homelab.ValidateTerraform
type HomelabValidateTerraformOpts struct {
	Source *Directory // homelab (../../../.dagger/terraform.go:260:2)

	Container *Container // homelab (../../../.dagger/terraform.go:262:2)
}

// ValidateTerraform runs tofu init and tofu validate on all discovered Terraform modules.
// Each module is validated independently for parallel execution and individual
// error reporting.
// When paths are provided, only matching modules are validated.
func (r *Homelab) ValidateTerraform(ctx context.Context, opts ...HomelabValidateTerraformOpts) (string, error) { // homelab (../../../.dagger/terraform.go:257:1)
	if r.validateTerraform != nil {
		return *r.validateTerraform, nil
	}
	q := r.query.Select("validateTerraform")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabValidateWoodpeckerOpts contains options for Homelab.ValidateWoodpecker
type HomelabValidateWoodpeckerOpts struct {
	Source *Directory // homelab (../../../.dagger/main.go:216:2)

	Paths []string // homelab (../../../.dagger/main.go:218:2)

	Container *Container // homelab (../../../.dagger/main.go:220:2)
}

// ValidateWoodpecker lints Woodpecker CI pipeline configuration files
// When paths are provided, only matching files are linted
func (r *Homelab) ValidateWoodpecker(ctx context.Context, opts ...HomelabValidateWoodpeckerOpts) (string, error) { // homelab (../../../.dagger/main.go:213:1)
	if r.validateWoodpecker != nil {
		return *r.validateWoodpecker, nil
	}
	q := r.query.Select("validateWoodpecker")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `paths` optional argument
		if !querybuilder.IsZeroValue(opts[i].Paths) {
			q = q.Arg("paths", opts[i].Paths)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HomelabVerifyCacheGranularityOpts contains options for Homelab.VerifyCacheGranularity
type HomelabVerifyCacheGranularityOpts struct {
	//
	// scripts/*.sh is here because gomodhash.go go:embeds it; without it the
	// package will not build inside the container. .golangci.yaml is here
	// because golang_lint_test.go reads the repo's real config rather than a
	// stand-in, so the behaviour tests exercise the config the gate runs with.
	//
	Source *Directory // homelab (../../../.dagger/cachecheck.go:38:2)
	//
	// Run only tests matching this regexp, as `go test -run`. Defaults to all
	// of them, which covers the fake-backed tests too.
	//
	//
	// Default: "."
	Run string // homelab (../../../.dagger/cachecheck.go:43:2)
	//
	// The toolchain to run the tests in. It has to carry a Go toolchain; the
	// engine-backed tests additionally need the nesting enabled below.
	//
	Container *Container // homelab (../../../.dagger/cachecheck.go:47:2)
}

// VerifyCacheGranularity runs this module's cache-granularity tests, including
// the ones that need a real engine.
//
// `go test ./.dagger/...` on its own only exercises internal/daggerfake's model
// of the engine. The engine-backed tests in engine_cache_test.go skip unless
// they inherit a Dagger session, so they need either
//
//	cd .dagger && dagger run go test ./...
//
// or this function, which gets the same thing by running the tests in an exec
// with nesting enabled. Use it to confirm the fake still agrees with the engine
// after a Dagger upgrade, or after teaching the fake a new API call.
//
// Its result caches on its inputs, like any other function here, and that is
// the right behaviour: the two things that can change the verdict both bust it.
// Editing .dagger changes source, and upgrading Dagger means a new engine with
// a new cache. To force a re-run anyway, vary run (`--run '.*'` is a different
// argument to the default `.` and so a different call).
func (r *Homelab) VerifyCacheGranularity(ctx context.Context, opts ...HomelabVerifyCacheGranularityOpts) (string, error) { // homelab (../../../.dagger/cachecheck.go:30:1)
	if r.verifyCacheGranularity != nil {
		return *r.verifyCacheGranularity, nil
	}
	q := r.query.Select("verifyCacheGranularity")
	for i := len(opts) - 1; i >= 0; i-- {
		// `source` optional argument
		if !querybuilder.IsZeroValue(opts[i].Source) {
			q = q.Arg("source", opts[i].Source)
		}
		// `run` optional argument
		if !querybuilder.IsZeroValue(opts[i].Run) {
			q = q.Arg("run", opts[i].Run)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this Homelab as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Homelab) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// DevenvProject is a devenv project with a scoped source directory.
// Each DevenvProject carries only the files for its project, enabling
// per-project caching: changing files in one project won't invalidate
// the cache for other projects.
type HomelabDevenvProject struct { // homelab (../../../.dagger/devenv.go:49:6)
	query *querybuilder.Selection

	id   *ID
	path *string
}

func (r *HomelabDevenvProject) WithGraphQLQuery(q *querybuilder.Selection) *HomelabDevenvProject {
	return &HomelabDevenvProject{
		query: q,
	}
}

// A unique identifier for this HomelabDevenvProject.
func (r *HomelabDevenvProject) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *HomelabDevenvProject) XXX_GraphQLType() string {
	return "HomelabDevenvProject"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *HomelabDevenvProject) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *HomelabDevenvProject) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *HomelabDevenvProject) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *HomelabDevenvProject) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = HomelabDevenvProject{query: selectNode(dag.query, id, "HomelabDevenvProject")}
	return nil
}

// Path is the project's directory relative to the repo root (e.g. "." for the root project).
func (r *HomelabDevenvProject) Path(ctx context.Context) (string, error) { // homelab (../../../.dagger/devenv.go:51:2)
	if r.path != nil {
		return *r.path, nil
	}
	q := r.query.Select("path")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Source is the project's scoped source directory.
func (r *HomelabDevenvProject) Source() *Directory { // homelab (../../../.dagger/devenv.go:53:2)
	q := r.query.Select("source")

	return &Directory{
		query: q,
	}
}

// Update runs `devenv update` for this project, refreshing its devenv.lock
// with the latest commit for every input (nixpkgs, etc.). Returns the
// resulting changeset.
func (r *HomelabDevenvProject) Update() *Changeset { // homelab (../../../.dagger/devenv.go:80:1)
	q := r.query.Select("update")

	return &Changeset{
		query: q,
	}
}

// AsNode returns this HomelabDevenvProject as a Node.
// This is a local type conversion — no GraphQL call.
func (r *HomelabDevenvProject) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// GoModule is a Go module with a scoped source directory.
// Each GoModule carries only the files for its module, enabling
// per-module caching: changing files in one module won't invalidate
// the cache for other modules.
type HomelabGoModule struct { // homelab (../../../.dagger/golang.go:37:6)
	query *querybuilder.Selection

	id   *ID
	path *string
	test *string
}

func (r *HomelabGoModule) WithGraphQLQuery(q *querybuilder.Selection) *HomelabGoModule {
	return &HomelabGoModule{
		query: q,
	}
}

// A unique identifier for this HomelabGoModule.
func (r *HomelabGoModule) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *HomelabGoModule) XXX_GraphQLType() string {
	return "HomelabGoModule"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *HomelabGoModule) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *HomelabGoModule) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *HomelabGoModule) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *HomelabGoModule) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = HomelabGoModule{query: selectNode(dag.query, id, "HomelabGoModule")}
	return nil
}

// Lint runs `go mod tidy` followed by `golangci-lint run --fix` on this module,
// returning the resulting changes. Errors from either step (including unfixable
// lint issues that --fix leaves behind) are returned rather than swallowed, so
// LintGo fails when there's more to fix than autofixing can handle.
func (r *HomelabGoModule) Lint(configFile *File, container *Container) *Changeset { // homelab (../../../.dagger/golang.go:140:1)
	assertNotNil("configFile", configFile)
	assertNotNil("container", container)
	q := r.query.Select("lint")
	q = q.Arg("configFile", configFile)
	q = q.Arg("container", container)

	return &Changeset{
		query: q,
	}
}

// Path is the module's directory relative to the repo root (e.g. "cmd/lab").
func (r *HomelabGoModule) Path(ctx context.Context) (string, error) { // homelab (../../../.dagger/golang.go:39:2)
	if r.path != nil {
		return *r.path, nil
	}
	q := r.query.Select("path")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Source is the module's scoped source directory.
// When populated via GoModules(), this is derived from aparent directory, so its ID is stable across sessions.
func (r *HomelabGoModule) Source() *Directory { // homelab (../../../.dagger/golang.go:43:2)
	q := r.query.Select("source")

	return &Directory{
		query: q,
	}
}

// Test runs Go tests for this module.
func (r *HomelabGoModule) Test(ctx context.Context, container *Container) (string, error) { // homelab (../../../.dagger/golang.go:66:1)
	assertNotNil("container", container)
	if r.test != nil {
		return *r.test, nil
	}
	q := r.query.Select("test")
	q = q.Arg("container", container)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this HomelabGoModule as a Node.
// This is a local type conversion — no GraphQL call.
func (r *HomelabGoModule) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// KubernetesIntegrationReport is one release's JUnit XML report.
type HomelabKubernetesIntegrationReport struct { // homelab (../../../.dagger/integration.go:69:6)
	query *querybuilder.Selection

	id      *ID
	release *string
	xml     *string
}

func (r *HomelabKubernetesIntegrationReport) WithGraphQLQuery(q *querybuilder.Selection) *HomelabKubernetesIntegrationReport {
	return &HomelabKubernetesIntegrationReport{
		query: q,
	}
}

// A unique identifier for this HomelabKubernetesIntegrationReport.
func (r *HomelabKubernetesIntegrationReport) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *HomelabKubernetesIntegrationReport) XXX_GraphQLType() string {
	return "HomelabKubernetesIntegrationReport"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *HomelabKubernetesIntegrationReport) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *HomelabKubernetesIntegrationReport) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *HomelabKubernetesIntegrationReport) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *HomelabKubernetesIntegrationReport) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = HomelabKubernetesIntegrationReport{query: selectNode(dag.query, id, "HomelabKubernetesIntegrationReport")}
	return nil
}

// Release is the helmfile release the report is for.
func (r *HomelabKubernetesIntegrationReport) Release(ctx context.Context) (string, error) { // homelab (../../../.dagger/integration.go:71:2)
	if r.release != nil {
		return *r.release, nil
	}
	q := r.query.Select("release")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XML is the report's contents.
func (r *HomelabKubernetesIntegrationReport) XML(ctx context.Context) (string, error) { // homelab (../../../.dagger/integration.go:73:2)
	if r.xml != nil {
		return *r.xml, nil
	}
	q := r.query.Select("xml")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this HomelabKubernetesIntegrationReport as a Node.
// This is a local type conversion — no GraphQL call.
func (r *HomelabKubernetesIntegrationReport) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// KubernetesIntegrationRun is the outcome of one workflow run that got as far
// as running tests.
//
// Plain data only, and the reports as text rather than a Directory: a directory
// produced by execs that used a service and a secret cannot outlive the session
// that made it, and a function result holding one is not cached across sessions.
// The reports are small enough that nothing is lost.
type HomelabKubernetesIntegrationRun struct { // homelab (../../../.dagger/integration.go:57:6)
	query *querybuilder.Selection

	id      *ID
	summary *string
}

func (r *HomelabKubernetesIntegrationRun) WithGraphQLQuery(q *querybuilder.Selection) *HomelabKubernetesIntegrationRun {
	return &HomelabKubernetesIntegrationRun{
		query: q,
	}
}

// Failed names the releases whose tests did not all pass. Empty is a pass;
// an infrastructure failure is an error instead, not an entry here.
func (r *HomelabKubernetesIntegrationRun) Failed(ctx context.Context) ([]string, error) { // homelab (../../../.dagger/integration.go:65:2)
	q := r.query.Select("failed")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this HomelabKubernetesIntegrationRun.
func (r *HomelabKubernetesIntegrationRun) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *HomelabKubernetesIntegrationRun) XXX_GraphQLType() string {
	return "HomelabKubernetesIntegrationRun"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *HomelabKubernetesIntegrationRun) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *HomelabKubernetesIntegrationRun) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *HomelabKubernetesIntegrationRun) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *HomelabKubernetesIntegrationRun) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = HomelabKubernetesIntegrationRun{query: selectNode(dag.query, id, "HomelabKubernetesIntegrationRun")}
	return nil
}

// Reports holds one JUnit XML report per release.
func (r *HomelabKubernetesIntegrationRun) Reports(ctx context.Context) ([]HomelabKubernetesIntegrationReport, error) { // homelab (../../../.dagger/integration.go:62:2)
	q := r.query.Select("reports")

	q = q.Select("id")

	type reports struct {
		Id ID
	}

	convert := func(fields []reports) []HomelabKubernetesIntegrationReport {
		out := []HomelabKubernetesIntegrationReport{}

		for i := range fields {
			val := HomelabKubernetesIntegrationReport{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "HomelabKubernetesIntegrationReport")
			out = append(out, val)
		}

		return out
	}
	var response []reports

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// Summary is the per-release verdict, with pytest's output folded in for
// the ones that failed.
func (r *HomelabKubernetesIntegrationRun) Summary(ctx context.Context) (string, error) { // homelab (../../../.dagger/integration.go:60:2)
	if r.summary != nil {
		return *r.summary, nil
	}
	q := r.query.Select("summary")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this HomelabKubernetesIntegrationRun as a Node.
// This is a local type conversion — no GraphQL call.
func (r *HomelabKubernetesIntegrationRun) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// PythonProject is one Python project — a directory with a pyproject.toml —
// carrying only that project's files, so changing one project does not
// invalidate the BuildKit cache for the others.
type HomelabPythonProject struct { // homelab (../../../.dagger/python.go:43:6)
	query *querybuilder.Selection

	id   *ID
	path *string
	test *string
}

func (r *HomelabPythonProject) WithGraphQLQuery(q *querybuilder.Selection) *HomelabPythonProject {
	return &HomelabPythonProject{
		query: q,
	}
}

// Format runs black on this project, returning the resulting changes.
func (r *HomelabPythonProject) Format(container *Container) *Changeset { // homelab (../../../.dagger/python.go:202:1)
	assertNotNil("container", container)
	q := r.query.Select("format")
	q = q.Arg("container", container)

	return &Changeset{
		query: q,
	}
}

// A unique identifier for this HomelabPythonProject.
func (r *HomelabPythonProject) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *HomelabPythonProject) XXX_GraphQLType() string {
	return "HomelabPythonProject"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *HomelabPythonProject) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *HomelabPythonProject) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *HomelabPythonProject) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *HomelabPythonProject) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = HomelabPythonProject{query: selectNode(dag.query, id, "HomelabPythonProject")}
	return nil
}

// Path is the project's directory relative to the repo root
// (e.g. "k8s/foundation/kured/files/kured-webhook").
func (r *HomelabPythonProject) Path(ctx context.Context) (string, error) { // homelab (../../../.dagger/python.go:46:2)
	if r.path != nil {
		return *r.path, nil
	}
	q := r.query.Select("path")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Source is the project's scoped source directory.
func (r *HomelabPythonProject) Source() *Directory { // homelab (../../../.dagger/python.go:48:2)
	q := r.query.Select("source")

	return &Directory{
		query: q,
	}
}

// Test runs pytest for this Python project, in the given toolchain container.
//
// No -m here on purpose. Which markers an ordinary run excludes is a per-project
// decision, declared in each pyproject.toml's addopts — and it has to be,
// because a command-line -m replaces addopts rather than narrowing it. Passing
// one from here would re-enable the tests a project deselected for itself, and
// deselect the ones a project runs deliberately: jellyfin-exporter registers
// `integration` precisely so those tests run by default against its stub server.
func (r *HomelabPythonProject) Test(ctx context.Context, container *Container) (string, error) { // homelab (../../../.dagger/python.go:106:1)
	assertNotNil("container", container)
	if r.test != nil {
		return *r.test, nil
	}
	q := r.query.Select("test")
	q = q.Arg("container", container)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this HomelabPythonProject as a Node.
// This is a local type conversion — no GraphQL call.
func (r *HomelabPythonProject) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// HomelabOpts contains options for Query.Homelab
type HomelabOpts struct {
	DevenvSource *Directory // homelab (../../../.dagger/main.go:42:2)
}

// New captures the devenv definition the toolchain container is built from.
func (r *Query) Homelab(opts ...HomelabOpts) *Homelab { // homelab (../../../.dagger/main.go:39:1)
	q := r.query.Select("homelab")
	for i := len(opts) - 1; i >= 0; i-- {
		// `devenvSource` optional argument
		if !querybuilder.IsZeroValue(opts[i].DevenvSource) {
			q = q.Arg("devenvSource", opts[i].DevenvSource)
		}
	}

	return &Homelab{
		query: q,
	}
}
