apiVersion: v2
name: kured
description: KUbernetes REboot Daemon
version: 0.0.10
appVersion: "1.22.1"

dependencies:
  - name: kured
    version: "5.12.1"
    repository: https://kubereboot.github.io/charts
