apiVersion: v2
name: kured
description: KUbernetes REboot Daemon
version: 0.0.9
appVersion: "1.22.0"

dependencies:
  - name: kured
    version: "5.12.0"
    repository: https://kubereboot.github.io/charts
