apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: kanidm-transport
  namespace: {{ .Release.Namespace }}
spec:
  insecureSkipVerify: true # Kanidm is using self-signed certificate
