apiVersion: v2
name: longhorn
description: Distributed block storage
version: 0.1.10
appVersion: 1.13.0

dependencies:
  - name: longhorn
    version: 1.13.0
    repository: https://charts.longhorn.io
