apiVersion: v2
name: longhorn
description: Distributed block storage
version: 0.1.7
appVersion: 1.11.2

dependencies:
  - name: longhorn
    version: 1.11.2
    repository: https://charts.longhorn.io
