apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.renovate.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      data:
        RENOVATE_TOKEN: {{` "{{ .giteaToken }}" `}}
        RENOVATE_GITHUB_COM_TOKEN: {{` "{{ .githubToken }}" `}}
  data:
    - secretKey: giteaToken
      remoteRef:
        key: gitea.renovate
        property: token
    - secretKey: githubToken
      remoteRef:
        key: github.renovate
        property: token
