kind: ENC[AES256_GCM,data:BZHeb8RF,iv:8JKbQ17c8O4ZFUyYUc6XM3OcwTxeP3qhY1ht976mZTA=,tag:V6j8PBD+3KvV7CuH6lX+sw==,type:str]
ansible_user: ENC[AES256_GCM,data:CFKge6uWCjM=,iv:2eyz3gKc5h1CRAWbaLXjJW998yqC8Sm9KU5hnOAzP5Y=,tag:qt2fHbXj083In5l6jjWmow==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:MyFQGNM9TkEs72FJyzbk4xP/AuA=,iv:cwHmEwxZsrKc+YpOmEV05VCNTIPpeox3G4xGvK3TycI=,tag:X8sxTjcJexzZJCSZkGFfAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ux6jahdtqlrcf3q5n0050vm2sr5qh66m388nfaamct6s643cspdqz8c40f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWkwwdktVVUFWWFFoMnAr
            UDR0UzkzWEk0MC9PbllyTU5YM1h1Nmo1QnhvCmlJVkxHcU1ESFlyeEJzcG9sNkc2
            Yy9kcStjWE45L20rV3AwQWk5VmljL2sKLS0tIFdVZytxTlBuR1gyKzI1UzJyVXlW
            WlJPVW90WG1MU1VBd3JUNUprRlRKYWMKQwd2s2bhdrv1r/lbmu26Q0x+S9/BSr86
            FHrBEienTbzDVR+bu//uysyebvuX+WaS8qkIgwPElaOyok5QvqdRYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T21:11:36Z"
    mac: ENC[AES256_GCM,data:0Bg6AIGIbxe54pnSyEOdBliwUS8P/ogWF4AHQ3ZqpJKWZLWE7LTOuesxS/Lskg1vx/P8r6NHwcgxfv0IjtgxDzDYErWcsEvi2ZY9G4CffZYBXGKH9oPBGZNf4WXditWAIS9Qt6zvPiXWPohwET3bxDEHM4v200K8384BYrA+lx8=,iv:aqNYVxjwUO20MkH1RX/CXoocxrNhM71vAxbtFp64hXI=,tag:VEqPSMfFRtKh+g/9tCSRzw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
