kind: ENC[AES256_GCM,data:UzocjgbN,iv:ddO3VkejQh+bKMRGYKaWnTEO13BYAeH05t3SEjbIsWk=,tag:CHZwXPQGXczt7kJNrvAd5A==,type:str]
ansible_user: ENC[AES256_GCM,data:59CI1R7mxxw=,iv:X1xDqslBWMDEV6DtxWcvFlPZM/5SxVih8+ZUbQNVy5k=,tag:+Zonb73JVhgZrHrCyAYLlQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:nq5H1hYsMVkzAsXTKOq13TBNuS8=,iv:/wLlnVJXheshmKEt8I6LvfaC/yYFzXWc+8irZD4LvZU=,tag:fcz+0Ih/ld5qjBvm6oY6xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ux6jahdtqlrcf3q5n0050vm2sr5qh66m388nfaamct6s643cspdqz8c40f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNnphamZ5TFpLOGJsR3o1
            MnowYXgwdUlGd2NBenorL3czNTBvWkVJN0hZCk1qRnRQaEthaFQrTHRpcnlBRXJC
            U2JWWDJMN3VFNE5obUpDd1NxVkZaQTgKLS0tIEdoWDVWTlV5UUVqS2daVE1LQytH
            MmdzTVhjdW5vU2NEOFZJSFJDWUVvSUEKJ325Wk4DLEOsReWd/bTyUbSQ/AASxkKd
            jUAaobjfMZbq8iHrfHuEmJjCvpU82tZvSkaR+y+tZ0I/O+aHxXEcWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T22:44:51Z"
    mac: ENC[AES256_GCM,data:i+hNwvHe4FpOLIaLUvE8TRrRpZWo4gdLgRU/S6PAG367/sgPcefzqBINykNC2SteX69hi69mMejjZs6kqs0On7YWYpJF5VqrgqWr/w5K5uT8CraK2bb6T6SenQf/56gyu0cT/dFD9aY6mGPtI1W4NtbnAtbB97nxZfptUpyB2d4=,iv:sqn8JI4fQFAn/0Flc+YZLuLiIUwmaxRS1VD16AuaFu8=,tag:Wop/XgZMFurs0tFmpOJK/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
