apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: longhorn-drop-default-group-when-nondefault-present
  namespace: {{ .Release.Namespace }}
spec:
  validationFailureAction: audit
  background: false
  rules:
    - name: remove-default-group-label
      match:
        any:
          - resources:
              kinds: ["PersistentVolumeClaim"]
      preconditions:
        all:
          # 1) PVC currently has the default group label set to "enabled"
          - key: "{{ `{{ request.object.metadata.labels.\"recurring-job-group.longhorn.io/default\" }}` }}"
            operator: Equals
            value: "enabled"
          # 2) There exists at least one *other* group label under recurring-job-group.longhorn.io/*
          - key: "{{ `{{ length(keys(request.object.metadata.labels)[?contains(@, 'recurring-job-group.longhorn.io/') && @ != 'recurring-job-group.longhorn.io/default']) }}` }}"
            operator: GreaterThan
            value: 0
      mutate:
        patchesJson6902: |-
          - op: remove
            path: /metadata/labels/recurring-job-group.longhorn.io~1default
