apiVersion: v2
name: argocd
version: 0.0.66
dependencies:
  - name: argo-cd
    version: 10.9.4
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 2.0.6
    repository: https://argoproj.github.io/argo-helm
  - name: argo-events
    version: 2.4.27
    repository: https://argoproj.github.io/argo-helm
