apiVersion: v2
name: argocd
version: 0.0.43
dependencies:
  - name: argo-cd
    version: 9.7.1
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 2.0.5
    repository: https://argoproj.github.io/argo-helm
  - name: argo-events
    version: 2.4.22
    repository: https://argoproj.github.io/argo-helm
