apiVersion: v2
name: authelia
version: 0.0.35
dependencies:
  - name: authelia
    version: 0.11.22
    repository: https://charts.authelia.com
  - name: app-template
    version: 5.2.1
    repository: https://bjw-s-labs.github.io/helm-charts
