apiVersion: v2
name: authelia
version: 0.0.27
dependencies:
  - name: authelia
    version: 0.11.6
    repository: https://charts.authelia.com
  - name: app-template
    version: 5.0.1
    repository: https://bjw-s-labs.github.io/helm-charts
