---
apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-default-agent-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: WOODPECKER_AGENT_SECRET
    secret-generator.v1.mittwald.de/length: "64"
type: Opaque
data: {}
