metallb:
  loadBalancerClass: metallb
  # disable frr as it was causing issues with kernel 6.18
  speaker:
    frr:
      enabled: false
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
  prometheus:
    rbacPrometheus: false
    serviceMonitor:
      enabled: false
