apiVersion: v2
name: gitea
version: 0.0.3
# renovate datasource=github-releases depName=go-gitea/gitea extractVersion=^v(?<version>.*)$
appVersion: 1.24.4
dependencies:
  - name: gitea
    version: 12.1.3
    repository: https://dl.gitea.io/charts/
