# https://github.com/dagger/dagger/blob/main/helm/dagger/values.yaml
dagger-helm:
  engine:
    # https://docs.dagger.io/reference/configuration/engine/
    # insecureRootCapabilities: effectively equivalent to running actions with `docker run --privileged`
    configJson: |
      {
        "logLevel": "info",
        "security": {
          "insecureRootCapabilities": false
        }
      }
    kind: StatefulSet
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "4"
        memory: 8Gi
    # use PVC instead of host path for data volume
    hostPath:
      dataVolume:
        enabled: false

    statefulSet:
      persistentVolumeClaim:
        enabled: true
        storageClassName: longhorn-rc1
        accessModes: [ReadWriteOnce]
        labels:
          recurring-job.longhorn.io/source: "enabled"
          recurring-job-group.longhorn.io/ephemeral: "enabled"
        resources:
          requests:
            storage: 80Gi
