# https://github.com/dagger/dagger/blob/main/helm/dagger/values.yaml
dagger-helm:
  engine:
    image:
      ref: registry.dagger.io/engine:v0.21.8
    # https://docs.dagger.io/reference/configuration/engine/
    # insecureRootCapabilities: effectively equivalent to running actions with `docker run --privileged`
    configJson: |
      {
        "logLevel": "info",
        "security": {
          "insecureRootCapabilities": false
        },
        "gc": {
          "enabled": true,
          "maxUsedSpace": "55GB",
          "minFreeSpace": "15%"
        }
      }
    kind: StatefulSet
    resources:
      limits:
        cpu: "8"
        memory: 16Gi
      requests:
        cpu: "4"
        memory: 8Gi
    # use local-path PVC instead of host path for data volume
    hostPath:
      dataVolume:
        enabled: false

    statefulSet:
      persistentVolumeClaim:
        enabled: true
        storageClassName: local-path
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 80Gi
