apiVersion: v2
name: kyverno
description: Kubernetes Native Policy Management
version: 0.0.2
appVersion: "v1.13.4"

dependencies:
  - name: kyverno
    version: 3.4.0
    repository: https://kyverno.github.io/kyverno
