kyverno:
  grafana:
    enabled: true

  admissionController:
    metricsService:
      create: true

  backgroundController:
    metricsService:
      create: true

  cleanupController:
    metricsService:
      create: true

  reportsController:
    metricsService:
      create: true
