# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/trust.cert-manager.io/bundle_v1alpha1.json
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: cluster-ca-bundle  # Name also used as the target ConfigMap name in each namespace
  namespace: {{ .Release.Namespace }}
spec:
  sources:
  - secret:
      name: "internal-ca-cert"
      key: "ca.crt"
  target:
    configMap:
      key: "root-certs.pem"
