apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:sog9hsuoZY48Pvo4mC2A76riET9VRQbRwQ==,iv:ng4ftPA+5QZ4EOiZR5G2R7mdBAvHzDME3peS0cn8AfM=,tag:zHqvkdkvArW2aoy7s06TTw==,type:str]
    api-token: ENC[AES256_GCM,data:Ts34L2SxhbSiymqIGfTdWh04rqWSQbwstNLJrvKXaG0uUPnLzezkhw==,iv:weIEhS93TIS/BBL4ja55CAaV2w2Etp4ADLT0yX9k/kw=,tag:81BZG+e4ZJ4IwZeZU+wcBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ux6jahdtqlrcf3q5n0050vm2sr5qh66m388nfaamct6s643cspdqz8c40f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZWZzYnFJcVo1WExMMm9i
            VUo2Qi9SeVBsd2U1MXk1ZTQ5cm9NbURVZVhjCmNOWTVWcTVVWXROUExkeGRWNXVi
            bTZ0UTNPOUlDSFhtQ0VwVUZNT3Q2dnMKLS0tIHI4bk0xUlZ0azJmdFQrTUVYcHFX
            eUhuOGg3YmVKb21FS1BFb3phK2dpbjQKOnl9VGpAIdFX3wjhnSBqlRD147xr8T8C
            6DQUBuRovi1XyYOzcSrTgHsa24JcYq4L7UjtEMnUgBvfcVsBwwT4Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T21:15:15Z"
    mac: ENC[AES256_GCM,data:Ucg0DWxIOnTFEu7EpTQwDoF99ZySi+uCIHh2I+Q53j1b3UeZdMGxCrnxdojVnZcINjUusrtbpizqO/Si6UZdGxjThfFAMv0d4v6L6zN94LfyGbjujwdguzbhco1DoHCzy/x15XWbBSY8M8dvfC9yZpupeNxj+agp1W1yEoS/HF8=,iv:6ODXKT+WQNRh2MqvalLdiy9tdEiKC8hbzCPcgK1/LZQ=,tag:1pCHCGn+LU0ZkBnc0hAmMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
