apiVersion: v2
name: oauth2-proxy
description: oauth2-proxy as a Traefik forwardAuth middleware, fronting Authelia OIDC
type: application
version: 0.0.2
dependencies:
  - name: oauth2-proxy
    version: 10.6.0
    repository: https://oauth2-proxy.github.io/manifests
