---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/
# https://github.com/PyratLabs/ansible-role-k3s

# (bool) Specify if a host (or host group) are part of the control plane
k3s_control_node: false

# (dict) k3s settings for all worker nodes
k3s_agent:
  node-ip: "{{ ansible_host }}"
  kubelet-arg:
    # The default /etc/resolv.conf managed by systemd-resolved
    # points to a caching service on localhost.
    # Coredns makes requests from localhost,
    # which leads to an infinite loop of resolving.
    # Tell kubelet to use the host's resolv.conf that contains the upstream resolvers only.
    - "resolv-conf=/run/systemd/resolve/resolv.conf"
