# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.psql.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: 2
  imageName: {{ .Values.psql.image }}
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: longhorn-rc2
  enableSuperuserAccess: true
  postgresql:
    # postgresql configuration options (postgresql.conf)
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
      # Reduce checkpoint frequency to lower I/O spikes (default 5min)
      checkpoint_timeout: 15min
      # Increase WAL size to allow less frequent checkpoints
      max_wal_size: 2GB
  monitoring:
    enablePodMonitor: true
  # Disable pod disruption budget so that the cluster can be shut down
  enablePDB: false
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "2Gi"
  backup:
    barmanObjectStore:
      endpointURL: http://s3proxy.s3-proxy.svc.cluster.local
      destinationPath: s3://postgres/{{ .Values.psql.clusterName }}/
      s3Credentials:
        accessKeyId:
          name: cnpg-s3-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-s3-credentials
          key: SECRET_ACCESS_KEY
      data:
        # https://cloudnative-pg.io/documentation/1.16/backup_recovery/#compression-algorithms
        compression: bzip2
    retentionPolicy: "14d"
    target: prefer-standby
  bootstrap:
    initdb:
      database: gitea
      owner: gitea
