apiVersion: v2
name: homepage
description: Homepage dashboard
type: application
version: 0.3.2
appVersion: "v2.0.0"
dependencies:
  - name: homepage
    version: 5.1.1
    repository: oci://ghcr.io/m0nsterrr/helm-charts
