{{/*
The Secret every dedicated oauth2-proxy instance consumes via
`oauth2-proxy.config.existingSecret`.

Three keys, none of them committed to git:
  client-id      stable identifier, must equal the Authelia OIDC client_id
  client-secret  autogenerated by mittwald secret-generator
  cookie-secret  autogenerated, 32 bytes -> AES-256 session cookie

The two reflector annotations are load-bearing and the reason this template
exists: auth-system's PreSync job mirrors this Secret in via reflector and
bcrypt-hashes client-secret into the aggregate Secret Authelia mounts, so no
hash is ever produced by hand. Omit them and the job waits for a mirror that
reflector will never fill. See
k8s/platform/auth-system/files/oidc-client-secrets/README.md.

Usage:
  {{- include "oauth2ProxyInstance.secret" . }}

Values (under .Values.oauth2ProxyInstance):
  clientId        required, must equal the Authelia client_id
  secretName      required, must equal oauth2-proxy.config.existingSecret
  labelsTemplate  optional name of a named template rendering the consuming
                  chart's common labels (e.g. "copyparty.labels")
*/}}
{{- define "oauth2ProxyInstance.secret" -}}
{{- $v := .Values.oauth2ProxyInstance | default dict -}}
{{- if not $v.clientId -}}
{{- fail "oauth2ProxyInstance.clientId is required and must equal the Authelia OIDC client_id" -}}
{{- end -}}
{{- if not $v.secretName -}}
{{- fail "oauth2ProxyInstance.secretName is required and must equal oauth2-proxy.config.existingSecret" -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $v.secretName }}
  namespace: {{ .Release.Namespace }}
  {{- with $v.labelsTemplate }}
  labels:
    {{- include . $ | nindent 4 }}
  {{- end }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: cookie-secret,client-secret
    secret-generator.v1.mittwald.de/length: "32"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: auth-system
type: Opaque
stringData:
  client-id: {{ $v.clientId }}
{{/* Trailing newline is deliberate: it keeps a following `{{- include ... }}`
     from chomping into this last line, where `---` would silently become part of
     the client-id value rather than a document separator. */}}
{{ end -}}
