# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/longhorn.io/recurringjob_v1beta2.json
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: trim-daily
  namespace: {{ .Release.Namespace }}
spec:
  concurrency: 1
  cron: 0 4 * * ?
  groups:
  - default
  labels:
    job: trim-daily
  name: trim-daily
  retain: 0
  task: filesystem-trim
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-daily
  namespace: {{ .Release.Namespace }}
spec:
  concurrency: 1
  cron: 0 0 * * *
  groups:
  - default
  labels:
    job: snapshot-daily
  name: snapshot-daily
  retain: 1
  task: snapshot
