exemptions:
  - controllerNames:
      - loki-helm-test
    rules:
      - privilegeEscalationAllowed
      - runAsRootAllowed
      - tagNotSpecified
  - controllerNames:
      - monitoring-system-prometheus-node-exporter
    rules:
      - hostNetworkSet
      - hostPIDSet
      - privilegeEscalationAllowed
  - controllerNames:
      - monitoring-system-promtail
    rules:
      - runAsRootAllowed
