#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "bcrypt>=4.2.0",
#     "kubernetes>=31.0.0",
# ]
# ///
"""
Authelia OIDC client secret sync.

Authelia reads each confidential client's secret from a file mounted out of the
`authelia-oidc-client-secrets` Secret, and expects a *bcrypt hash* rather than
the plaintext. The plaintext itself is generated by mittwald secret-generator in
the consuming app's own namespace (alongside that app's cookie-secret), because
the upstream oauth2-proxy chart wants client-id/client-secret/cookie-secret in a
single Secret.

This script closes that gap so no hash ever has to be produced by hand:

1. For each configured client, create a reflector "pull" Secret in this
   namespace that mirrors the app's Secret (reflector fills in the data), then
   wait for the plaintext to show up.
2. bcrypt-hash each plaintext into the aggregate target Secret. Existing hashes
   are *verified* against the plaintext first, so an unchanged secret is a
   no-op — bcrypt is salted, and re-hashing unconditionally would rewrite the
   Secret and restart Authelia on every single sync.
3. Drop keys and mirrors for clients that are no longer configured.
4. Restart Authelia only if an existing hash actually changed (i.e. the
   plaintext was rotated). Adding or removing a client changes Authelia's
   ConfigMap, and the chart's own `authelia.com/checksum-config` annotation
   already rolls the Deployment for that.

Runs as an ArgoCD PreSync hook: if a plaintext never arrives the hook fails, the
sync is blocked, and Authelia's ConfigMap is never advanced to reference a client
whose hash is missing. ArgoCD's retry backoff covers the case where this app and
the consuming app are pushed together and the app's namespace lands second.

The target Secret is deliberately NOT templated by the chart — this script owns
it outright (same pattern as authelia-oidc-jwks), which keeps ArgoCD from
applying an empty `data: {}` over the hashes mid-sync.
"""

import base64
import os
import sys
import time
from datetime import datetime, timezone

import bcrypt
from kubernetes import client, config
from kubernetes.client.rest import ApiException

# Label applied to every Secret this script creates, so mirrors can be found
# again for pruning without guessing from names alone.
MANAGED_BY_LABEL = "app.kubernetes.io/managed-by"
MANAGED_BY_VALUE = "authelia-oidc-client-secrets-sync"
CLIENT_ID_LABEL = "authelia.msng.to/oidc-client-id"

REFLECTS_ANNOTATION = "reflector.v1.k8s.emberstack.com/reflects"


class SourceRef:
    """A client's plaintext secret: which Secret to mirror, and which key in it."""

    def __init__(self, namespace: str, name: str, key: str):
        self.namespace = namespace
        self.name = name
        self.key = key

    @property
    def reflects(self) -> str:
        return f"{self.namespace}/{self.name}"

    def __eq__(self, other) -> bool:
        return isinstance(other, SourceRef) and (
            self.namespace,
            self.name,
            self.key,
        ) == (other.namespace, other.name, other.key)

    def __repr__(self) -> str:
        return f"SourceRef({self.reflects}:{self.key})"


def parse_client_sources(raw: str, default_key: str) -> dict[str, SourceRef]:
    """Parse CLIENT_SOURCES into {client_id: SourceRef}.

    Format is one entry per line (or comma-separated):
        <client_id>=<namespace>/<secret-name>[:<key>]
    Blank lines and `#` comments are ignored.
    """
    sources: dict[str, SourceRef] = {}
    for chunk in raw.replace(",", "\n").splitlines():
        entry = chunk.strip()
        if not entry or entry.startswith("#"):
            continue

        client_id, sep, location = entry.partition("=")
        client_id = client_id.strip()
        if not sep or not client_id:
            raise ValueError(
                f"malformed entry {entry!r}: expected <client_id>=<ns>/<secret>[:<key>]"
            )

        location, _, key = location.strip().partition(":")
        namespace, sep, name = location.partition("/")
        if not sep or not namespace.strip() or not name.strip():
            raise ValueError(
                f"malformed source {location!r} for client {client_id!r}: expected <ns>/<secret>"
            )

        if client_id in sources:
            raise ValueError(f"duplicate entry for client {client_id!r}")

        sources[client_id] = SourceRef(
            namespace.strip(), name.strip(), key.strip() or default_key
        )
    return sources


def needs_rehash(plaintext: str, existing_hash: str | None) -> bool:
    """True if the stored hash is missing, unusable, or not a hash of plaintext."""
    if not existing_hash:
        return True
    try:
        return not bcrypt.checkpw(plaintext.encode(), existing_hash.encode())
    except ValueError:
        # Not a valid bcrypt hash (e.g. a hand-written placeholder) — replace it.
        return True


def hash_secret(plaintext: str, cost: int) -> str:
    """bcrypt-hash a plaintext the way `authelia crypto hash generate bcrypt` does."""
    return bcrypt.hashpw(
        plaintext.encode(), bcrypt.gensalt(rounds=cost, prefix=b"2b")
    ).decode()


def mirror_name(prefix: str, client_id: str) -> str:
    return f"{prefix}{client_id}"


def plan_target_changes(
    existing: dict[str, str],
    plaintexts: dict[str, str],
    cost: int,
) -> tuple[dict[str, str | None], bool]:
    """Work out the patch for the aggregate Secret.

    Returns (patch, restart_needed). Keys mapped to None are removals — a
    strategic merge patch deletes those. restart_needed is True only when an
    already-present hash changed, meaning the plaintext was rotated and
    Authelia's ConfigMap won't change to trigger a rollout on its own.
    """
    patch: dict[str, str | None] = {}
    restart_needed = False

    for client_id, plaintext in sorted(plaintexts.items()):
        stored = existing.get(client_id)
        if not needs_rehash(plaintext, stored):
            continue
        patch[client_id] = hash_secret(plaintext, cost)
        if stored:
            restart_needed = True

    for client_id in sorted(existing):
        if client_id not in plaintexts:
            patch[client_id] = None

    return patch, restart_needed


def decode_data(secret) -> dict[str, str]:
    """Decode a V1Secret's base64 data into {key: str}."""
    return {k: base64.b64decode(v).decode() for k, v in (secret.data or {}).items()}


def encode_patch(patch: dict[str, str | None]) -> dict[str, str | None]:
    """base64-encode patch values, preserving None removals."""
    return {
        k: (None if v is None else base64.b64encode(v.encode()).decode())
        for k, v in patch.items()
    }


class Syncer:
    def __init__(self, api: client.CoreV1Api, apps: client.AppsV1Api, cfg: dict):
        self.api = api
        self.apps = apps
        self.namespace = cfg["namespace"]
        self.target_secret = cfg["target_secret"]
        self.mirror_prefix = cfg["mirror_prefix"]
        self.deployment = cfg["deployment"]
        self.timeout = cfg["timeout"]
        self.poll_interval = cfg["poll_interval"]
        self.cost = cfg["cost"]

    def ensure_mirror(self, client_id: str, source: SourceRef) -> str:
        """Create (or correct) the reflector pull Secret for a client."""
        name = mirror_name(self.mirror_prefix, client_id)
        body = client.V1Secret(
            metadata=client.V1ObjectMeta(
                name=name,
                namespace=self.namespace,
                labels={
                    MANAGED_BY_LABEL: MANAGED_BY_VALUE,
                    CLIENT_ID_LABEL: client_id,
                },
                annotations={REFLECTS_ANNOTATION: source.reflects},
            ),
            type="Opaque",
        )
        try:
            self.api.create_namespaced_secret(self.namespace, body)
            print(f"  created mirror {name} -> {source.reflects}")
            return name
        except ApiException as exc:
            if exc.status != 409:
                raise

        # Already there — make sure it still points at the right source, which
        # matters when a consuming app moves namespace or renames its Secret.
        existing = self.api.read_namespaced_secret(name, self.namespace)
        current = (existing.metadata.annotations or {}).get(REFLECTS_ANNOTATION)
        if current != source.reflects:
            print(f"  repointing mirror {name}: {current} -> {source.reflects}")
            self.api.patch_namespaced_secret(
                name,
                self.namespace,
                {
                    "metadata": {"annotations": {REFLECTS_ANNOTATION: source.reflects}},
                    # Clear stale data so the wait below can't pass on the old
                    # source's value before reflector catches up.
                    "data": None,
                },
            )
        return name

    def wait_for_plaintexts(
        self, wanted: dict[str, tuple[str, SourceRef]]
    ) -> dict[str, str]:
        """Poll the mirrors until reflector has populated every plaintext."""
        plaintexts: dict[str, str] = {}
        deadline = time.monotonic() + self.timeout

        while True:
            pending = []
            for client_id, (name, source) in sorted(wanted.items()):
                if client_id in plaintexts:
                    continue
                secret = self.api.read_namespaced_secret(name, self.namespace)
                value = decode_data(secret).get(source.key)
                if value:
                    plaintexts[client_id] = value
                    print(
                        f"  reflected {client_id} from {source.reflects}:{source.key}"
                    )
                else:
                    pending.append(f"{client_id} ({source.reflects}:{source.key})")

            if not pending:
                return plaintexts

            if time.monotonic() >= deadline:
                raise TimeoutError(
                    f"reflector did not populate after {self.timeout}s: {', '.join(pending)}. "
                    "Check that each source Secret exists with the expected key, and carries "
                    "reflection-allowed=true plus reflection-allowed-namespaces including "
                    f"'{self.namespace}'."
                )

            print(f"  waiting on {len(pending)} mirror(s): {', '.join(pending)}")
            time.sleep(self.poll_interval)

    def read_target(self) -> dict[str, str]:
        """Read the aggregate Secret, creating it empty if this is a fresh install."""
        try:
            return decode_data(
                self.api.read_namespaced_secret(self.target_secret, self.namespace)
            )
        except ApiException as exc:
            if exc.status != 404:
                raise

        print(f"  creating {self.target_secret}")
        self.api.create_namespaced_secret(
            self.namespace,
            client.V1Secret(
                metadata=client.V1ObjectMeta(
                    name=self.target_secret,
                    namespace=self.namespace,
                    labels={MANAGED_BY_LABEL: MANAGED_BY_VALUE},
                ),
                type="Opaque",
            ),
        )
        return {}

    def apply_target(self, patch: dict[str, str | None]) -> None:
        self.api.patch_namespaced_secret(
            self.target_secret,
            self.namespace,
            {"data": encode_patch(patch)},
        )

    def prune_mirrors(self, keep: set[str]) -> None:
        """Delete mirrors for clients that are no longer configured."""
        secrets = self.api.list_namespaced_secret(
            self.namespace,
            label_selector=f"{MANAGED_BY_LABEL}={MANAGED_BY_VALUE}",
        )
        for secret in secrets.items:
            name = secret.metadata.name
            if name == self.target_secret or not name.startswith(self.mirror_prefix):
                continue
            client_id = (secret.metadata.labels or {}).get(CLIENT_ID_LABEL)
            if client_id in keep:
                continue
            print(f"  pruning stale mirror {name}")
            self.api.delete_namespaced_secret(name, self.namespace)

    def restart_authelia(self) -> None:
        """Roll the Authelia Deployment so it re-reads the mounted secret files.

        Authelia resolves client secrets at startup only, so a rotated hash needs
        a restart. This is the same patch `kubectl rollout restart` issues; the
        annotation is listed in the Application's ignoreDifferences so ArgoCD
        does not strip it back off on the next sync.
        """
        stamp = datetime.now(timezone.utc).isoformat()
        print(f"  restarting deployment/{self.deployment}")
        self.apps.patch_namespaced_deployment(
            self.deployment,
            self.namespace,
            {
                "spec": {
                    "template": {
                        "metadata": {
                            "annotations": {"kubectl.kubernetes.io/restartedAt": stamp}
                        }
                    }
                }
            },
        )


def load_config() -> dict:
    namespace = os.environ.get("NAMESPACE")
    if not namespace:
        raise ValueError("NAMESPACE is required")

    default_key = os.environ.get("SOURCE_KEY", "client-secret")
    sources = parse_client_sources(os.environ.get("CLIENT_SOURCES", ""), default_key)

    return {
        "namespace": namespace,
        "target_secret": os.environ.get(
            "TARGET_SECRET", "authelia-oidc-client-secrets"
        ),
        "mirror_prefix": os.environ.get("MIRROR_PREFIX", "oidc-client-mirror-"),
        "deployment": os.environ.get("AUTHELIA_DEPLOYMENT", ""),
        "timeout": int(os.environ.get("REFLECTION_TIMEOUT", "180")),
        "poll_interval": int(os.environ.get("POLL_INTERVAL", "3")),
        "cost": int(os.environ.get("BCRYPT_COST", "12")),
        "sources": sources,
    }


def main() -> int:
    cfg = load_config()
    sources: dict[str, SourceRef] = cfg["sources"]

    try:
        config.load_incluster_config()
    except config.ConfigException:
        config.load_kube_config()

    api = client.CoreV1Api()
    apps = client.AppsV1Api()
    syncer = Syncer(api, apps, cfg)

    if not sources:
        print("No OIDC clients configured; nothing to do.")
        return 0

    print(f"Syncing {len(sources)} OIDC client secret(s) into {cfg['target_secret']}")

    print("Ensuring reflector mirrors...")
    wanted = {
        cid: (syncer.ensure_mirror(cid, ref), ref)
        for cid, ref in sorted(sources.items())
    }

    print("Waiting for reflected plaintexts...")
    plaintexts = syncer.wait_for_plaintexts(wanted)

    print("Reconciling hashes...")
    existing = syncer.read_target()
    patch, restart_needed = plan_target_changes(existing, plaintexts, cfg["cost"])

    if patch:
        added = sorted(
            k for k, v in patch.items() if v is not None and k not in existing
        )
        updated = sorted(k for k, v in patch.items() if v is not None and k in existing)
        removed = sorted(k for k, v in patch.items() if v is None)
        for label, keys in (
            ("added", added),
            ("updated", updated),
            ("removed", removed),
        ):
            if keys:
                print(f"  {label}: {', '.join(keys)}")
        syncer.apply_target(patch)
    else:
        print("  all hashes already match their plaintexts; nothing to do")

    syncer.prune_mirrors(set(sources))

    if restart_needed:
        if cfg["deployment"]:
            syncer.restart_authelia()
        else:
            print("  a hash changed but AUTHELIA_DEPLOYMENT is unset; skipping restart")

    print("Done.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (
        Exception
    ) as exc:  # noqa: BLE001 - hook should fail loudly and block the sync
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
