---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Denver"
  KUBE_VIP_ADDR: "10.69.1.254"
  METALLB_LB_RANGE: "10.69.1.220-10.69.1.230"
  METALLB_K8S_GATEWAY_ADDR: "10.69.1.220"
  METALLB_INGRESS_ADDR: "10.69.1.221"
