apiVersion: v2
name: csi-driver-nfs
version: 0.0.4
appVersion: "4.9.0"
dependencies:
  - name: csi-driver-nfs
    repository: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    version: 4.13.4
