{{- $rootContext := . -}}
{{- $basePath := "files"}}
{{- $folders := list "homepage-configs" -}}

{{- range $folder := $folders -}}
  {{- $sanitizedFolderRelativeToBasePath := regexReplaceAll "\\W+" (clean $folder) "-" -}}
  {{- if eq $sanitizedFolderRelativeToBasePath "-" -}}
    {{- $sanitizedFolderRelativeToBasePath = base $folder -}}
  {{- end -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $sanitizedFolderRelativeToBasePath }}
  namespace: {{ $rootContext.Release.Namespace }}
data:
{{- range $path, $_ :=  $rootContext.Files.Glob  (printf "%s/%s/*" $basePath $folder) }}
  {{ $path | base }}: |-
    {{- $rootContext.Files.Get $path | trim | nindent 4 -}}
{{- end -}}
{{- end -}}
