---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gitea.gitea.admin.existingSecret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    secret-generator.v1.mittwald.de/type: basic-auth
    secret-generator.v1.mittwald.de/basic-auth-username: gitea_admin
data: {}
