apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-msng-to
  # namespace must match traefik's
  namespace: kube-system
spec:
  secretName: msng-to-tls
  dnsNames:
    - "msng.to"
    - "*.msng.to"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
