---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ template "authelia.name" . }}
  namespace: {{ template "authelia.namespace" . }}
  labels: {{ include "authelia.labels" (merge (dict "Labels" .Values.authelia.ingress.labels) .) | nindent 4 }}
  {{- with $annotations := include "authelia.annotations" (merge (dict "Annotations" .Values.authelia.ingress.annotations) .) }}
  annotations: {{ $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- with $refs := .Values.authelia.ingress.gatewayAPI.parentRefs }}
  parentRefs:
    {{- range $ref := $refs }}
    - name: {{ $ref.name | squote }}
      {{- if $ref.sectionName }}
      sectionName: {{ $ref.sectionName }}
      {{- end }}
      {{- if $ref.namespace }}
      namespace: {{ $ref.namespace }}
      {{- end }}
      {{- if $ref.port }}
      port: {{ $ref.port }}
      {{- end }}
    {{- end }}
  {{- end }}
  hostnames:
    {{- if .Values.authelia.ingress.gatewayAPI.hostnamesOverride }}
    {{- range $host := .Values.authelia.ingress.gatewayAPI.hostnamesOverride }}
    - {{ . | squote }}
    {{- end }}
    {{- else }}
    {{- range $cookie := .Values.authelia.configMap.session.cookies }}
    - {{ (include "authelia.ingress.host" (merge (dict "SubDomain" $cookie.subdomain "Domain" $cookie.domain) $)) | squote }}
    {{- end }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: 'PathPrefix'
            value: {{ (include "authelia.path" $) | squote }}
      backendRefs:
        - name: {{ include "authelia.name" $ }}
          port: {{ include "authelia.service.port" $ }}
