apiVersion: ENC[AES256_GCM,data:HyI=,iv:0tNfCiZW6r262hBwOMs5s8QOliAoceoVU7fxMP3F8EQ=,tag:0n+19yA+eME8spaRF8Ov6Q==,type:str]
clusters:
    - cluster:
        certificate-authority-data: ENC[AES256_GCM,data:D8kIgCZttUzJjM3aJ6ba3Ibjo3WCqo16gPRlcOXrjTx6MSB+GiMezgLYspu1flZb2gETVBk0o89YdRpzeoOEoeD1DxzPXSwOr9xO9a1JfzLgOgT6gt74nq2FTHi9BAeU20tjMbsUjnJMcm5MsFAFScf4eonxogRE6acLQaH0OoJ6OVwvnFtR4BImK6vGXw5kFdXi6lTk52uY7dQ3UjxlzhsxTzLDTFuuHaSVjr/Pf1Vhaffd3h2ZUAwNpwXxPMV+jjjBguYJ5wJ+aKcNQyKkvyJHaszlqCeso0RKOjD8hQlgqj/q8cPr8Vy8PGWiQyin1cahrKsBTGQaZqdTye3QJcjwpv0PHhqxz2sba6vahxrp1eKJ0IH1Heqb9PhOkmcZkFoeM+g9dGn9U37THGfJi9MJydiNj2D2XxQjt1jo9nOQYNsmUjEpYGJCfmYsV1omnRFIIn9ju+/nu3aCYw6M7P9xuK9NiuHGZpBwocNMwEKbxnPRmQcSsDMWO+aMdzN7B3hjL3L1vE8+nsikyC+8yFgeZp5Hb0wMEk1rlr0/A8QRW5pwjRZpcahz1Q4gzes2ZdVZiLbIdPkf9FpZ1jq3xO9aXPhh4Qx51UX7LPoo9ZBF8mBfLtPvbNfWHUEmRd38WLgkmH1xjswqoEj499CjN39oT4OwCODMVSuPK36FlfaJKNBwp5qcu/8rTcVMrKPAAE0AFi0W7M3V5a+C36ka6HoSCj9YJG4pR8CLZZCO9kg0DuOJOZXztCHYSpNeto5tjhx6o5148mikD2kq54f1fB0J0vwjrgSYPRdsfZNrzYoIxvyjfN0WnZaCboI/+12BLBYQkmLBJVrtfrVetNUtBsOIxEUjVpFdyo92oz06YYxX2erPd1piYGKZEhthCVE3qeWi9AC9+XYbidW4XWPHir9La3iA0CpyVRnb+92tkCGz0gktO9/i3CttVdmint53pdbRgny1Uv3ARM0/qx2x1luEnqNAHDGgEqpsv3bPJfRnimp1oEOCjw==,iv:LBHix/N02LzY1axJ7CUzjnsnp3Qg2dH/lHLk/EtPU4A=,tag:On2mV3vxhKJb7JExgv/MXw==,type:str]
        server: ENC[AES256_GCM,data:3x4e6rsD3moo/4oMRXmrt4G2sTn+D4y6xg==,iv:kqg+h2HWhzWjiNwYDSmpwxXj7m1WujkqY9MmJc+tl2o=,tag:/Yy/1Gah/phPX0axOthOvw==,type:str]
      name: ENC[AES256_GCM,data:HbO62szaDw==,iv:e/YAVNUYpTTioYtHeBDgz0Whtk9+dXeVnmb4WUs2SVU=,tag:ihxEzgRIiC4DDKWUlzWypg==,type:str]
contexts:
    - context:
        cluster: ENC[AES256_GCM,data:ITdNLmy82Q==,iv:/bvHbjDuuhTf1WoRQLEZ4kGUYXkIYpCYAH+RySx75Ak=,tag:mOtC2fIiN6v9g6hNAng3RQ==,type:str]
        user: ENC[AES256_GCM,data:MPjRVaB1MQ==,iv:DmrlJNyCIDmc7FZy0cmWTlVUsRxW+cfcYN9NMcMMPIk=,tag:Tqt/3iyj1qg89SQX6WjhLQ==,type:str]
      name: ENC[AES256_GCM,data:W3AAtPeUrQ==,iv:TLCbknp35qU4w1VQPXpwXMY4syR/S6WoFX0KSWpe2N0=,tag:y/+HXccM6L/msZSGnfrHsw==,type:str]
current-context: ENC[AES256_GCM,data:B9Lgs3yFnw==,iv:1wieHfJ16whzqzE4uT20vk+TbJzzZd47xnnNqZqis6k=,tag:9ZDck7BPwKVcIwcvR+Ezow==,type:str]
kind: ENC[AES256_GCM,data:Cz7r3USi,iv:r3CpECQqGzE5YA+tyxtK5gbIAk+IUOd8rnEFxUcdZRs=,tag:+PHNYtgwQ4JT0g3VR7GIKQ==,type:str]
users:
    - name: ENC[AES256_GCM,data:to/IL2ghAw==,iv:X8jnrl4N+y5LIK/5IhLWuyb2wlL1P884oXNgnLbVkQQ=,tag:obRUZeH2Dx0u7co5wV+eww==,type:str]
      user:
        client-certificate-data: ENC[AES256_GCM,data:ohXcYsq03oXXXak3Qthtre3H4qts7TJEQRtOXxB3fIq16W57gPumHaJst6IV632AGVG+gV/i5KPKN9J89t9cj+iWIVEcaCKPT+6LQLypOswIXKjZXU3Gh5VfqdmfiAgHPhcR8F+PkKQpKv7KeV0srmDxuG0ps5MhaJG3Sry/t8JkMc/nq1D1n3iM6aibhfvw+K0c3riLJBkSpKj3GgBu/GVeCpsKQBqSbxb/Zztkp0x6zWsq3VZUT83K6+Az59v8ILhYUz29fEEkJUApSup7qqMXyUVN/TUNZa6caLcwoAPm6NqUpnQkmQSrjKaLQy/zYexdSMBaZRUnaXIqfjtAx5CuFQ27J2rRGLlSUYEoiDy3yw22WwOCMZqsptgqwymFLLo3W1dFPUOYGE8+Jw4dFyV4H5XfvLgYT7w9Knw9mZs9oidklV108Vd/35vBEqBGoJc4zYwb23x6GjOAWwgcQ4vQgyK/9QpIOkoqvXu6vUizULB1IolAROC8wTlnDQWcAZSR9KMeML6D10ORygvun6li42QTa2XzaMhfX3lcYc7PWdcn+lWsKlC1h0NWtCwQf2puH/1UnsfiAoDjOcmK/iS5tisM43Affq0XpWg+cZC/b7ng07SiHXFVI29tBUneyx7QVMDQYdUwd9c0cC14HBLJSZsbH9Xf2DhrHwo2lUn7w1dKUTpjwTO0lsLI82EgTvV8UC2oW4L/7HELsf7AYJWGKBmb2cMn1NQNsp/GFfcwlAVPN6uE5gAe/u5gvdvlsBUqfjDLY4dqCN9lvaYvvFiKzNJfqUg3YhULsKlP5HEle7D3l5ZgORFybadLYUpJ3v9zNs8dL4Vad22/2Qk/bCsLgOPQJleNgFQ4xBNLJ1W1KF0JmhXvNC1yNBHMmDOQcpYG8fTvSLisHqMeoSeIGBYp1iaSYelwpIjNOHEEI3kY8gbumy3YZuh8XwB2yC3bSq+o2LRgd1+xUIS1eRy5FY9qhkBKmaqmGYZ4yZIvw3sbO5wz0kuciwzzwDUhGpZT536k81LbBn+yTcfRvmVEiS7q6GV5G+cr1/uu3kNebX6FDcV5YDuNI8RieORe24fZ0DXN6pVelTipoFjCGc4mHmAOq8PjQ/fMo1kRLuBchi/ht4rvPbj4zgPAU5WYJOSOUJ9AF0Ga2S0BpP/d/JKXi+jlIyv8YB48wTsIHvPK887gp8EQMIYO08+EvazgleIrr4AGOjv4uJj4zXd7enzck0r3jTy4PNk7aQLJtQU3ZYhwwvT5AdJ1G6SEU/yZiSIbS/CbppvMmb1TFPRe97RudVQJ4Sr4I02/AJrQaHQYciGDcQb/JUhQWgRRGUSIitOtcSu60zSVqGqMN8d6ptXBcMwRk6bctg0DQ/2ThrdtH0ZaEoFkDuqnAy2Go0tJF3TkfChjs3+AIlw7msgMSM0Jw6UcPn8lxKJtSVg6tVEyPNWlt39vlUovTcoi+sFNWWJAxobCKzJlln2702K1Pf00dHhlAii3U88znNl8SxgGo7YCXfKW1yFFRntvn/Bv5mCtTIlHUY8Azn7WfuJ5E6Zt/d1xS+qXODMkEcGuQ23u6HFNTVaLFXJdNauC5y4zU0YI6FOqeHh1dir8G3GMMy0Ctc6UvenNalxcYreY3isRedpRUCtQJlqAM+Z9fP54q6hTv1bSL7d55VuQOs7bTpACNdXmgBsUPt+9KH8mKgNSmcz5zyAmxpEzVMD3DNSimtUZ2644kM8OApWJOPMEqHzlK05Mdd+RLdO3YscP54NOrPP0gUcf3Mb1OS0Xq9mozFYVlNFLFJfYBx54RJqKM6z0TuhM4fxjAcAIbmZtmSQAvYn0+c0F3e8B12Aw1yjMBtC0i8/WKhl4FD47L1Ogr/eNXsZRAyqZh+1hCgjIG7EDQkimkyA7VC9koIJlA/hPhMiYIS4St2dFOYNuqYj7LxZu4hIbPdpJGAxu2fbv8KowknPDFR1hom9oMmbJJ/bmR9GmS604gAnZEA3kcqaO/TmbECbFs9pY/7QNM5xvYoX32cAR6XrlYPx48x7xhnwhf0KdoUXF0dVxD0LHlwMqzqYVFq7vZ47Hi0oie0nJK5kJDgJL28m2,iv:Tx7R3zvDB9+j1SAACzCUsNm2Pu1BRH9grvrAVou3MVY=,tag:yQUxEBXFVHbYBglrYSsGLw==,type:str]
        client-key-data: ENC[AES256_GCM,data:Lx10D1cPez1ruv+IXWdqwPTs8dvtWdZmeUT270ccl2yZm7sp5JHqX4DuBiLGwz/WLhhcRCayJNbo+sVwVPiIgjpD4eCDNfPjGu/iMI9SFKueWDsb5pAh9bY9iM/GPtdEoYEQlBQYGN0agjjeYH8ekEltRM4u1qDqjufAaBU7crbhRtkuZEJr9sBmqEkM/01rYjSAGSqDqkQJzshmr8kpJCmHJFmBH4uuIDCicH/bdCfvsMDFhcIrFGKpBlPU+ggES2TR6bzj7YmnRF9vNqpWuoyplBMsSK9+R6kxNTQCeAV6acfnJNuLX+IE+KTN4aFWkS87WX+XWqzIeF+/ALeFkDZvvgDGsFoDF4wNiK3DDkDUns/jpN930xrOVlokU+zSUOiwNXW4tWbmpgz5GRK7eg==,iv:0xCLZhTWorAe8lQG+/0KydEBnBHcVu+pIiDCiiXAOow=,tag:kMIvaYzdEBcbNVVTu118kg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUStqbGVEVXZvQ1Y5eUxN
            NUZ1UlR0WjEwMTZpZXdLM2NXdVRGSFdiRTBjClk1K0ZpcThTM2VKQ3pDbXdtMVAv
            aVhvR3MwMk5wVDZ2eHdxNUhCeE5qS28KLS0tIHUza3FUVjZmOU1aRXBVL1RxUExy
            eG5LSGZmRjFxSGdrSmdIL09Dc0VadE0Kuz3t6AIu6x0qqaIexrp14ZtL9hs0nEqO
            C75csbxXl+IMDPLn/F801R7WeSqUFaqHyinQSeQnWNMxhsFJaiYS9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ux6jahdtqlrcf3q5n0050vm2sr5qh66m388nfaamct6s643cspdqz8c40f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYTNyQjNXZTMyL2Y5OWZR
            OTdnbGp0MFlPYmZYdGdkSlN6TGs2cWo4SzFnClZVNllwYVk2SHhZMThqcjhoeTRE
            UVlPVS9zcSsxaXNsak9KdGhHTFRaNDQKLS0tIGI4Q3cvSVpNNHpUa3ZsczQ0WWJC
            S2VUSmJlNHYxeTZuT3ZtUDlSWnpMU2sKWmbWgcQUs0CpiX+o9DR4eK6n3i78/sPm
            4LlEGnIh/syIN3gDTYpYH8Ats1Mud8nxfADCOuNxKrfkSXjfw/JJ5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age134rsuzlwf7fqzl3zluzjmheez6y4x5mmakfsejpjenr6qy3st3rs3rd5l9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2L1U3K1FRTkxSNW5TTHdX
            SHV6QVZuL3BrOE1oWEJXY3cxb0dUWVRrWnpBCmkraG9Nc05LdVJPT0ZEK3J0Vmpm
            SlB5a3lwQmdKQ3NDcmcvbE9KeFp6dXMKLS0tIG10ZlhTNXVGcUNWcjJONmVrRHZ3
            WThzU3RZMmpIWkpZWG41YmhsUlhUOFkKh/jZigLyu6ABH5R5hNm1tXazyAdYV2xQ
            W2BAeEauoQrMQI+TDrB2MWCcmhm4CJH3hf4VXd1Dr/V3KIPQ8OjJ4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sytxxylgnjkdev2qjds6zdwn6ynt73tn4u7lvg27cjdwj97lj4xs75ycyf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5N2h2VnVmZmRWYjZwYVBw
            WHdCQ1BNWnVxZW1BYXlZWkowbm9kdTRkWFZjCjZ6TGNEZEUwUVFtR2VkbHdYREpQ
            SjV6UDc5Y1FSN3kxaEplWkI1ckdMeGsKLS0tIDZ0TGM0VHo5YW5GNUFnOWJhZ2Zn
            c08vNS9nMlhLU3pYZVdEdTFJRE5IbDQKLLm6N89bii7jvYIr/TE0PKCpUMfCmenC
            oZwXFgtxvvfjggVtgAnWUwZMAX01IXFIDCdhENn2qngQ5UT6Sy7Dhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12uwv74ykhvs45aftm8d4v03ry44jdkt93nmslhktc2u4fq7j7yyqg5zdph
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaLzlqS3hFSWk1N042RFNi
            ZzByclp3emR0UjBLaDJjdEtiYzAxRXIzMVRnCnBrdFI0MXgrNW9TaUZ6Yit0N3U3
            aUx5WTF3UlE0cERjSHdQVHRkTXhGNU0KLS0tIGtpMVNuN2l6VE1NVmRxMlJ5YUE2
            dmJuVnA0THFucEZPWGMzOXN1UEV4b0kKNKwqlZrwsuag5GHVR9/fjUflOoxRVN//
            SbnCNmeLKyzThfY7Kyzwr8Zv61i6Qha7cMAeikrc2DTr026gQ829hA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y8n63p4zrlzxphe9k7hlc27vhk3g3k32nz0p4eg66tz4p2pnjavq4aq3xp
    lastmodified: "2026-08-19T17:05:27Z"
    mac: ENC[AES256_GCM,data:zEQUa1n2mDWEi4R02KzN+npsjolp5OG5Ds3FYp8UIzwalopRDhGY5m71oNu/+dyFBp1vZmWkAiNyuqLLS62A8tJxyT3/gJUxzg2/oBGMoyWvYIQSU+lOfNt4+lExPem5Zda8Ja43SfGkpbEQeJ+bn30EPDrqvTROuTGZtuYPLZE=,iv:vkzs1iC8NLjt6gU4lcy7GqxnmI1BelIG04KMd4gFTZg=,tag:MmkYK8fgzYLls1IwaEXw8Q==,type:str]
    pgp:
        - created_at: "2025-10-27T21:40:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DAAAAAAAAAAASAQdAV7pJRQM6jt3WUr5SA0hRw3kI3sVG+GG31fMh7f+nchsw
            zuoFDivSKFJbA0sGrTRthtTOF5Ms2DH07gjJjcVq+wZmbcT7h8KnrINHMEpJ1cyI
            0l4B4xaaWq08UFzxYXhBQayXL++y6Xk9DcC0UUtAKXhZYG32ytguSq36w/0Fmrvh
            Ec6gByYQugyQpR/KTyh4sMJ+CMTTcokjptxcjEnvYZw9SODZNsKhehnWSfI+VtS2
            =LGA/
            -----END PGP MESSAGE-----
          fp: FD5B1635F2218760E010601F4A6E1024D7BBE968
    unencrypted_suffix: _unencrypted
    version: 3.13.3
