repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator
releases:
  - name: glados-tts
    namespace: glados-tts
    chart: incubator/raw
    values:
      - resources:
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: glados-tts-models-pvc
            spec:
              storageClassName: longhorn-rc1
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: glados-tts
              labels:
                app: glados-tts
            spec:
              replicas: 1
              # scale down current deployment before upgrading
              # Added because my poor Atom-based node can't handle two pods at once.
              strategy:
                type: Recreate
              selector:
                matchLabels:
                  app: glados-tts
              template:
                metadata:
                  labels:
                    app: glados-tts
                spec:
                  initContainers:
                    - name: model-downloader
                      image: "pcloud/gdown"
                      command:
                        [
                          "/bin/sh",
                          "-c",
                          "if ! ls -1 /models/emb; then gdown https://drive.google.com/uc?id=1nEpr51IEdmCd3IJaPXykhk1oYgpcy1Qn -O /tmp/models.zip; unzip /tmp/models.zip -o -d /models; fi",
                        ]
                      volumeMounts:
                        - name: models
                          mountPath: /models
                  containers:
                    - name: glados-tts
                      image: ghcr.io/teekennedy/glados_tts_remote:7c459a5
                      ports:
                        - containerPort: 8124
                      volumeMounts:
                        - name: models
                          mountPath: /app/models
                          readOnly: true
                  volumes:
                    - name: models
                      persistentVolumeClaim:
                        claimName: glados-tts-models-pvc
          - apiVersion: v1
            kind: Service
            metadata:
              name: glados-tts-service
              namespace: glados-tts
            spec:
              selector:
                app: glados-tts
              ports:
                - protocol: TCP
                  port: 8124
                  targetPort: 8124
          - apiVersion: traefik.io/v1alpha1
            kind: IngressRoute
            metadata:
              name: glados-tts-ingress
              namespace: glados-tts
            spec:
              entryPoints:
                - web
                - websecure
              routes:
                - kind: Rule
                  match: Host(`glados-tts.msng.to`)
                  services:
                    - kind: Service
                      name: glados-tts-service
                      port: 8124
