repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: incubator
    url: https://charts.helm.sh/incubator
releases:
  - name: longhorn-nixos
    namespace: longhorn-system
    chart: incubator/raw
    values:
      - resources:
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: longhorn-nixos-path
              namespace: longhorn-system
            data:
              PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/run/wrappers/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.7.2
    needs:
      - longhorn-nixos
    jsonPatches:
      - target:
          kind: DaemonSet
          name: longhorn-manager
          namespace: longhorn-system
        patch:
          - op: add
            path: /spec/template/spec/containers/0/envFrom
            value:
              - configMapRef:
                  name: longhorn-nixos-path
      - target:
          kind: Deployment
          name: longhorn-driver-deployer
          namespace: longhorn-system
        patch:
          - op: add
            path: /spec/template/spec/containers/0/envFrom
            value:
              - configMapRef:
                  name: longhorn-nixos-path
      - target:
          kind: Job
          namespace: longhorn-system
        patch:
          - op: add
            path: /spec/template/spec/containers/0/envFrom
            value:
              - configMapRef:
                  name: longhorn-nixos-path
          - op: replace
            path: /spec/ttlSecondsAfterFinished
            value: 3600
