apiVersion: v2
name: argocd
version: 0.0.17
dependencies:
  - name: argo-cd
    version: 9.1.0
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-apps
    version: 2.0.2
    repository: https://argoproj.github.io/argo-helm
