argo-cd:
  server:
    metrics: &metrics
      enabled: false
      serviceMonitor:
        enabled: false
  controller:
    metrics: *metrics
  repoServer:
    metrics: *metrics
  redis:
    metrics: *metrics
argocd-apps:
  applicationsets:
    root:
      generators:
        - git:
            repoURL: &repoURL https://github.com/teekennedy/k8s-homelab
            revision: &revision main
            directories:
              - path: foundation/*
              - path: platform/*
              # - path: apps/*
      template:
        metadata:
          name: '{{path.basename}}'
        spec:
          project: default
          source:
            repoURL: *repoURL
            targetRevision: *revision
          destination:
            name: in-cluster
            namespace: '{{path.basename}}'
