---
# OIDC client secrets for various clients
apiVersion: v1
kind: Secret
metadata:
  name: authelia-oidc-client-secrets
  namespace: {{ .Release.Namespace }}
stringData:
  copyparty: '$2b$12$5ZEqIhQ9proDImmlbb0XQOMr3newPf61Pkh3CVl4tDB1MvQalsF5C'
  oauth2-proxy: '$2b$12$407JaO6LrgVmhnL4tO46vOcZwW4vsM0qTTHAXXpuJF7TkhNxOTTDy'
  oauth2-proxy-internal: '$2b$12$rDLnW0tP8RhDrelNhajlGendwesVQ.hx.9xHq154ShVdzSb8HBgCG'

