apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: authelia
  namespace: {{ .Release.Namespace }}
  labels:
    prometheus: kube-prometheus
    role: alert-rules
spec:
{{ .Files.Get "files/authelia-rules.json" | indent 2 }}
