---
# NAS-backed static PV for vmbackup.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: victoria-metrics-backups
spec:
  capacity:
    storage: {{ .Values.backup.nfs.capacity }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.2
    - xprtsec=mtls
  nfs:
    server: {{ .Values.backup.nfs.server }}
    path: {{ .Values.backup.nfs.path }}
  claimRef:
    name: victoria-metrics-backups
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-metrics-backups
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: victoria-metrics-backups
  resources:
    requests:
      storage: {{ .Values.backup.nfs.capacity }}
