apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: woodpecker
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: woodpecker
  ignoreDifferences:
    - jsonPointers:
        - /spec/volumeName
        - /spec/storageClassName
        - /spec/resources/requests/storage
      kind: PersistentVolumeClaim
    - jsonPointers:
        - /data
      kind: Secret
      name: woodpecker-gitea-oauth2
      namespace: woodpecker
    - jsonPointers:
        - /data
      kind: Secret
      name: woodpecker-default-agent-secret
      namespace: woodpecker
  project: default
  source:
    path: k8s/platform/woodpecker
    repoURL: http://gitea-http.gitea:3000/ops/k8s-homelab
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    retry:
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 16m
      limit: 10
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
