# https://github.com/woodpecker-ci/helm/tree/main/charts/woodpecker
woodpecker:
  server:
    createAgentSecret: false
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
    env:
      WOODPECKER_HOST: "https://ci.msng.to"
      WOODPECKER_GITEA: "true"
      WOODPECKER_GITEA_URL: "https://git.msng.to"
      WOODPECKER_ADMIN: "tkennedy"
    extraSecretNamesForEnvFrom:
      - woodpecker-default-agent-secret
      - woodpecker-gitea-oauth2
    persistentVolume:
      storageClass: longhorn
      labels:
        recurring-job.longhorn.io/source: "enabled"
        recurring-job-group.longhorn.io/backup: "enabled"
    ingress:
      enabled: true
      hosts:
        - host: ci.msng.to
          paths:
            - path: /
              backend:
                serviceName: woodpecker-server
                servicePort: 80
      tls:
        - hosts:
            - ci.msng.to

  agent:
    replicaCount: 1
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
    env:
      WOODPECKER_SERVER: "woodpecker-server:9000"
      WOODPECKER_BACKEND: "kubernetes"
      WOODPECKER_BACKEND_K8S_NAMESPACE: "woodpecker"
      WOODPECKER_BACKEND_K8S_STORAGE_CLASS: "local-path"
      WOODPECKER_BACKEND_K8S_STORAGE_RWX: "false"
      # Allow setting the serviceAccountName in workflows
      WOODPECKER_BACKEND_K8S_SERVICE_ACCOUNT_NAME_ALLOW_FROM_STEP: "true"
      # TODO get a base image with dagger CLI preinstalled and use that with a non-root user
      # WOODPECKER_BACKEND_K8S_SECCTX_NONROOT: "true"
      WOODPECKER_BACKEND_K8S_VOLUME_SIZE: "1G"
