woodpecker:
  server:
    env:
      WOODPECKER_HOST: "https://ci.msng.to"
      WOODPECKER_GITEA: "true"
      WOODPECKER_GITEA_URL: "http://gitea-http.gitea:3000"
      WOODPECKER_GITEA_OAUTH_URL: "https://git.msng.to"
      WOODPECKER_ADMIN: "tkennedy"
    extraSecretNamesForEnvFrom:
      - woodpecker-gitea-oauth2
    persistentVolume:
      storageClass: longhorn
    ingress:
      enabled: true
      hosts:
        - host: ci.msng.to
          paths:
            - path: /
              backend:
                serviceName: woodpecker-server
                servicePort: 80
      tls:
        - hosts:
            - ci.msng.to

  agent:
    replicaCount: 1
    env:
      WOODPECKER_SERVER: "woodpecker-server:9000"
      WOODPECKER_BACKEND: "kubernetes"
      WOODPECKER_BACKEND_K8S_NAMESPACE: "woodpecker"
      WOODPECKER_BACKEND_K8S_STORAGE_CLASS: "longhorn"
      WOODPECKER_BACKEND_K8S_VOLUME_SIZE: "1G"
