when:
  - event: pull_request

steps:
  - name: ci
    image: alpine:3
    environment:
      _EXPERIMENTAL_DAGGER_RUNNER_HOST: "kube-pod://dagger-engine-dagger-helm-engine-0?namespace=dagger-engine&container=dagger-engine"
      # Don't prompt for dagger cloud sign up
      DAGGER_NO_NAG: "1"
    backend_options:
      kubernetes:
        serviceAccountName: dagger-pipeline
    commands:
      - apk add --no-cache curl git kubectl jq
      - curl -fsSL https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.20.3 BIN_DIR=/usr/local/bin sh
      # Pre-build the devenv container using the host nix daemon for faster builds
      # - dagger call devenv --nix-daemon /nix/var/nix/daemon-socket/socket
      - |
        CHANGED=$(echo "$CI_PIPELINE_FILES" | jq -r '.[]')

        if [ -z "$CHANGED" ]; then
          echo "No changed files detected"
          exit 0
        fi

        dagger call all --source=. --paths "$(echo "$CI_PIPELINE_FILES" | jq -r 'join(",")')"
