when:
  - event: pull_request

steps:
  - name: ci
    image: alpine:3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
    environment:
      _EXPERIMENTAL_DAGGER_RUNNER_HOST: "kube-pod://dagger-engine-dagger-helm-engine-0?namespace=dagger-engine&container=dagger-engine"
      # Don't prompt for dagger cloud sign up
      DAGGER_NO_NAG: "1"
      DAGGER_VERSION: "0.20.5"
    backend_options:
      kubernetes:
        serviceAccountName: dagger-pipeline
    commands:
      - apk add --no-cache curl kubectl
      - curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=/usr/local/bin sh
      - dagger check
