apiVersion: v2
name: longhorn
description: Distributed block storage
version: 0.0.1
appVersion: "1.8.2"

dependencies:
  - name: longhorn
    version: 1.8.2
    repository: https://charts.longhorn.io
