---
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "forgejo-resources" "oidc" "clientSecretName" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: client-secret
    secret-generator.v1.mittwald.de/length: "32"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: auth-system
type: Opaque
